- xinference/client.py
- xinference/deploy/cmdline.py
fix type of class attribute `chat_history` which is changed in https://github.com/xorbitsai/inference/pull/103
> BUG: fix chat_history type

- xinference/core/gradio.py
- xinference/deploy/cmdline.py
- xinference/deploy/local.py
- xinference/deploy/supervisor.py
- xinference/model/__init__.py
- xinference/model/llm/__init__.py
> ENH: Add meta file to check if model is downloaded

- xinference/client.py
- xinference/conftest.py
- xinference/core/api.py
- xinference/core/gradio.py
- xinference/core/service.py
- xinference/core/tests/__init__.py
- xinference/core/tests/test_api.py
- xinference/deploy/supervisor.py
- xinference/tests/test_client.py
> ENH: client provides chat and gen interface

- xinference/deploy/cmdline.py
- xinference/deploy/local.py
- xinference/deploy/supervisor.py
- xinference/deploy/utils.py
- xinference/deploy/worker.py
Passing log level to subprocesses.
Resolve #115
> ENH: logging for subprocess

- xinference/core/service.py
> add error message while worker timeout

- xinference/core/service.py
> BUG: worker timeout during downloading

- README.md
> DOC: Add gif in readme

- xinference/deploy/supervisor.py
> ENH: auto find available port for API

- xinference/client.py
- xinference/core/restful_api.py
- xinference/core/tests/test_restful_api.py
- xinference/tests/test_client.py
> FEAT: implement chat and generate in RESTful client

- xinference/model/llm/__init__.py
- xinference/model/llm/core.py
> FEAT: support wizard-v1.1

- setup.cfg
- xinference/client.py
- xinference/core/restful_api.py
- xinference/core/service.py
- xinference/core/tests/test_restful_api.py
- xinference/tests/test_client.py
> ENH: Implement RESTful API stream generate

- xinference/model/llm/__init__.py
> FEAT: support vicuna-v1.3 33B

- xinference/model/llm/pytorch/core.py
> BUG: fix pytorch int8

- xinference/client.py
- xinference/core/model.py
- xinference/core/restful_api.py
- xinference/core/tests/test_api.py
- xinference/core/tests/test_restful_api.py
- xinference/model/llm/core.py
- xinference/model/llm/pytorch/core.py
- xinference/tests/test_client.py
> FEAT: Embedding

- xinference/model/llm/core.py
- xinference/model/llm/pytorch/core.py
> ENH: set default device to `mps` on MacOS

- README.md
- README_zh_CN.md
- xinference/client.py
- xinference/core/gradio.py
- xinference/model/llm/__init__.py
- xinference/model/llm/core.py
- xinference/model/llm/llama2.py
- xinference/tests/test_client.py
> FEAT: LLaMA-2

- examples/gradio_chatinterface.py
Response to #195, instructions are in the file comments
> ENH: add Gradio ChatInterface chatbot to example

- xinference/model/llm/pytorch/utils.py
> BUG: fix pytorch model generate bug when stream is True

- xinference/model/llm/pytorch/baichuan.py
- xinference/model/llm/pytorch/core.py
> BUG: fix baichuan-chat configure

- xinference/model/llm/__init__.py
> BUG: disable vicuna pytorch model

- README.md
- README_ja_JP.md
- README_zh_CN.md
I created Japanese translated README.
> DOC: Add Japanese README

- xinference/core/service.py
- xinference/model/llm/pytorch/core.py
> BUG: disable baichuan-chat and baichuan-base on macos

- xinference/model/llm/ggml/tests/test_chatglm.py
Update the ChatGLM tests after the code refactoring in #251
> TST: Update ChatGLM Tests

- xinference/core/gradio.py
- xinference/core/service.py
- xinference/model/llm/llm_family.py
- xinference/model/llm/tests/test_llm_family.py
> BUG: delete tqdm_class in snapshot_download

- xinference/core/service.py
- xinference/model/llm/ggml/chatglm.py
- xinference/model/llm/ggml/llamacpp.py
- xinference/model/llm/pytorch/core.py
> BUG: ChatGLM Parameter Switch

- xinference/model/llm/pytorch/core.py
fix https://github.com/xorbitsai/inference/issues/273
> BUG: fix import torch error even if user don't want to launch torch model

- xinference/core/gradio.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/pytorch/tests/__init__.py
- xinference/model/llm/pytorch/tests/test_opt.py
> FEAT: add opt-125m pytorch model and add ut

- setup.cfg
- xinference/model/llm/__init__.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/pytorch/baichuan.py
- xinference/model/llm/pytorch/compression.py
- xinference/model/llm/pytorch/core.py
- xinference/model/llm/pytorch/falcon.py
- xinference/model/llm/pytorch/utils.py
- xinference/model/llm/pytorch/vicuna.py
- xinference/model/llm/utils.py
> FEAT: support falcon 40b pytorch model

- benchmark/benchmark_script.py
- setup.cfg
- xinference/model/llm/tests/benchmark_script.py
> TST: add benchmark script

- benchmark/benchmark_script.py
> ENH: select q4_0 as default quantization method for ggmlv3 model in benchmark

- xinference/model/llm/__init__.py
> BUG: llm_family.json encoding

- examples/gradio_chatinterface.py
Resolves #295 
Let's disable Gradio telemetry.
Reference: https://www.gradio.app/docs/interface
> ENH: disable gradio telemetry

- xinference/model/llm/pytorch/core.py
> ENH: accelerate 4-bit quantization for pytorch model

- setup.cfg
> ENH: remove chatglmcpp from deps

- xinference/core/worker.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family.py
- xinference/model/llm/pytorch/core.py
- xinference/model/llm/pytorch/tests/test_opt.py
- xinference/model/llm/tests/test_llm_family.py
Resolves #317 
For GGML Model, all Model Revision are set to null for placeholder (later changes may appear and thus may change the revision)
For Pytorch Model, all revision are currently set to the latest commit on HuggingFace.
> ENH: Include model revision

- xinference/model/llm/core.py
- xinference/model/llm/ggml/llamacpp.py
- xinference/model/llm/pytorch/core.py
> BUG: fix mps and cuda device detection for pytorch model

- doc/source/models/custom.rst
- setup.cfg
- xinference/model/llm/llm_family.py
- xinference/model/llm/tests/test_llm_family.py
> ENH: cache from URI

- doc/source/models/custom.rst
- xinference/client.py
- xinference/core/tests/test_restful_api.py
- xinference/core/worker.py
- xinference/deploy/test/test_cmdline.py
- xinference/model/llm/ggml/tests/test_chatglm.py
- xinference/model/llm/ggml/tests/test_ctransformers.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family.py
- xinference/model/llm/tests/test_llm_family.py
- xinference/tests/test_client.py
Resolves #323 
Expected Effect:
> ENH: including default context length into model family

- xinference/core/restful_api.py
Resolves #385 
Testing if changing the `max_tokens` upper bound would break any unit tests.
> ENH: Update max_tokens to 32k

- doc/source/models/builtin/llama-2-chat.rst
- doc/source/models/builtin/llama-2.rst
- xinference/model/llm/__init__.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/pytorch/core.py
- xinference/model/llm/pytorch/llama-2.py
- xinference/model/llm/pytorch/llama_2.py
> FEAT: Support Llama-2 PyTorch model

- xinference/model/llm/pytorch/utils.py
> BUG: last token is duplicated

- xinference/model/llm/ggml/chatglm.py
> fix chatglm params

- doc/source/models/builtin/code-llama-python.rst
- doc/source/models/builtin/code-llama.rst
- doc/source/models/builtin/index.rst
- xinference/model/llm/llm_family.json
> FEAT: code-llama

- xinference/model/llm/pytorch/llama_2.py
> BUG: Asking to pad but the tokenizer does not have a padding token

- README.md
- README_ja_JP.md
- README_zh_CN.md
- doc/source/models/builtin/code-llama-instruct.rst
- doc/source/models/builtin/code-llama-python.rst
- doc/source/models/builtin/index.rst
- doc/source/models/builtin/llama-2-chat.rst
- doc/source/models/builtin/llama-2.rst
- xinference/model/llm/llm_family.json
- xinference/model/llm/tests/test_utils.py
- xinference/model/llm/utils.py
> FEAT: Support CodeLlama-Instruct

- xinference/web/ui/src/scenes/launch_model/index.js
resolve #430
Added edge cases for empty string / null when searching through registrations
> BUG: Searching in UI results in white screen

- MANIFEST.in
> BUG: Include json in MANIFEST.in

- xinference/client.py
- xinference/tests/test_client.py
> BUG: Fix restful client for embedding models

- doc/source/getting_started.rst
- doc/source/getting_started/accessing_models.rst
- doc/source/getting_started/index.rst
- doc/source/getting_started/installation.rst
- doc/source/getting_started/launching_models.rst
- doc/source/getting_started/troubleshooting.rst
- doc/source/getting_started/using_xinference.rst
- doc/source/index.rst
- doc/source/installation.rst
- doc/source/models/builtin/index.rst
- doc/source/user_guide/faq.rst
* add troubleshooting for huggingface no access problem
* add guides: installation, using xinference, launching models, accessing models
> DOC: Getting started guide for beginners

- xinference/core/supervisor.py
- xinference/core/worker.py
- xinference/web/ui/public/index.html
- xinference/web/ui/src/App.js
- xinference/web/ui/src/components/MenuSide.js
- xinference/web/ui/src/index.js
- xinference/web/ui/src/scenes/launch_model/index.js
- xinference/web/ui/src/scenes/launch_model/modelCard.js
- xinference/web/ui/src/scenes/register_model/index.js
- xinference/web/ui/src/scenes/running_models/index.js
- xinference/web/ui/src/theme.js
Add a page to register custom models, subject to change depending on #416
Screenshot:
> FEAT: add register model page for dashboard

- setup.cfg
> BUG: llama-cpp version dismatch

- xinference/model/embedding/model_spec.json
- xinference/model/llm/llm_family_modelscope.json
Fixes #512 
Tested on my Mac laptop.
> FEAT: Add BAAI/BGE v1.5 family models

- xinference/model/embedding/__init__.py
- xinference/model/embedding/core.py
- xinference/model/embedding/model_spec_modelscope.json
- xinference/model/embedding/tests/test_embedding_models.py
- xinference/model/llm/ggml/tests/test_chatglm.py
- xinference/model/llm/llm_family.py
- xinference/model/llm/tests/test_llm_family.py
- xinference/model/llm/tests/test_utils.py
- xinference/model/utils.py
Support models from ModelScope:
> ENH: Download embedding models from ModelScope

- xinference/web/ui/src/scenes/launch_model/modelCard.js
> ENH: display language tags

- xinference/web/ui/src/scenes/launch_model/index.js
> ENH: filter models by type

- xinference/model/embedding/model_spec_modelscope.json
> BUG: Fix `bge-base-zh` and `bge-large-zh` from ModelScope

- doc/source/examples/ai_podcast.rst
- doc/source/examples/chatbot.rst
- doc/source/examples/gradio_chatinterface.rst
- doc/source/examples/index.rst
- doc/source/examples/pdf_chatbot.rst
Add two more example pages and a few external tutorial permalinks
> DOC: Examples and resources page

- xinference/core/restful_api.py
- xinference/core/tests/test_restful_api.py
- Only support one system message.
- The system message should be the first one.
- Chat history does not contains system messages.
Fixes: https://github.com/xorbitsai/inference/issues/591
> BUG: Fix chat system messages

- setup.cfg
- xinference/client/oscar/actor_client.py
- xinference/client/restful/restful_client.py
- xinference/core/model.py
- xinference/core/restful_api.py
- xinference/model/image/core.py
- xinference/model/image/model_spec.json
- xinference/model/image/stable_diffusion/core.py
- xinference/model/image/tests/test_stable_diffusion.py
- New image_to_image API for image model.
- Compatible with openai createVariation API: https://platform.openai.com/docs/api-reference/images/createVariation
> FEAT: stable diffusion with controlnet

- .github/workflows/python.yaml
- xinference/client/tests/test_client.py
- xinference/deploy/test/test_cmdline.py
See https://llama-cpp-python.readthedocs.io/en/latest/changelog/
https://github.com/abetlen/llama-cpp-python/pull/798
> TST: Compatible with `llama-cpp-python` 0.2.12 

- xinference/api/__init__.py
- xinference/api/restful_api.py
- xinference/conftest.py
- xinference/core/chat_interface.py
- xinference/core/supervisor.py
- xinference/core/tests/test_worker.py
- xinference/core/utils.py
- xinference/core/worker.py
- xinference/deploy/cmdline.py
- xinference/deploy/local.py
- xinference/deploy/supervisor.py
- xinference/deploy/test/test_cmdline.py
- xinference/deploy/utils.py
- xinference/deploy/worker.py
- xinference/web/ui/src/scenes/launch_model/modelCard.js
- xinference/web/ui/src/scenes/running_models/index.js
This update addresses the following issues:
- Requests being blocked while another operation is in progress.
- Chat interface not responding in a streaming manner.
- Web UI redirects to the chat interface page even when the launch fails.
Resolves #316 #502 #516 #541 #540
> ENH: stateless supervisor and worker

- setup.cfg
- xinference/api/restful_api.py
- xinference/client/common.py
- xinference/client/tests/test_client.py
- xinference/core/model.py
- xinference/core/tests/test_restful_api.py
- Use `sse_starlette` handle fastapi stream response.
> BUG: Compatible with openai 1.1

- README.md
- README_zh_CN.md
- doc/source/models/builtin/Yi-200k.rst
- doc/source/models/builtin/Yi.rst
- doc/source/models/builtin/index.rst
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
Fixes #615 
Tested on 3090-TI Linux machine.
> FEAT: Support Yi Model

- setup.cfg
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family.py
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/pytorch/core.py
- Add https://huggingface.co/Qwen/Qwen-7B-Chat-Int4
- Add https://huggingface.co/Qwen/Qwen-7B-Chat-Int8
- Add https://huggingface.co/Qwen/Qwen-14B-Chat-Int4
- Add https://huggingface.co/Qwen/Qwen-14B-Chat-Int8
- Add https://modelscope.cn/models/qwen/Qwen-7B-Chat-Int4/summary
- Add https://modelscope.cn/models/qwen/Qwen-7B-Chat-Int8/summary
- Add https://modelscope.cn/models/qwen/Qwen-14B-Chat-Int4/summary
- Add https://modelscope.cn/models/qwen/Qwen-14B-Chat-Int8/summary
cmdline example: `xinference launch -n qwen-chat -f gptq -s 7 -q Int4`
> FEAT: Support gptq quantization

- xinference/core/utils.py
- xinference/core/worker.py
- xinference/model/llm/llm_family.py
Fixes: https://github.com/xorbitsai/inference/issues/673
> BUG: Fix custom model missing config json

- xinference/client/restful/restful_client.py
- xinference/client/tests/test_client.py
Fixes: https://github.com/xorbitsai/inference/issues/653
> BUG: Fix http error is not raised

- xinference/client/restful/restful_client.py
- xinference/model/llm/ggml/chatglm.py
- xinference/model/llm/ggml/tests/test_chatglm.py
> ENH: Add `generate` interface for `chatglm` with `ggml` format

- setup.cfg
Fixes: https://github.com/xorbitsai/inference/issues/649
> BUG: Fix pip install xinference[all]

- doc/source/getting_started/using_xinference.rst
Using this one command exec does not work.
> DOC: documentation for using xinference

- doc/source/getting_started/using_xinference.rst
- doc/source/models/builtin/index.rst
- doc/source/models/builtin/xverse-chat.rst
- doc/source/models/builtin/xverse.rst
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/tests/test_utils.py
- xinference/model/llm/utils.py
Fix #612 
Add support for verse models. Successfully tested  on a local V100 setup for the chat and complentation.
> FEAT: Xverse

- xinference/deploy/cmdline.py
- xinference/deploy/supervisor.py
> ENH: Specify actor pool port for distributed deployment

- xinference/model/embedding/__init__.py
- xinference/model/embedding/custom.py
- xinference/model/embedding/tests/test_embedding_models.py
- xinference/model/llm/llm_family.py
- Fixes: https://github.com/xorbitsai/inference/issues/689
- Fix custom embedding model is not loaded
> BUG: Fix xinference start failed if invalid custom model found

- xinference/web/ui/src/scenes/running_models/index.js
> ENH: [UI] Using tab in running models

- xinference/web/ui/src/scenes/launch_model/index.js
- xinference/web/ui/src/scenes/launch_model/launchRerank.js
- xinference/web/ui/src/scenes/launch_model/rerankCard.js
- xinference/web/ui/src/scenes/running_models/index.js
> ENH: [UI] supports launching rerank models

- xinference/core/model.py
- xinference/model/llm/vllm/core.py
Fixes: https://github.com/xorbitsai/inference/issues/725
Fixes: https://github.com/xorbitsai/inference/issues/726
> BUG: Fix vLLM backend

- xinference/api/restful_api.py
- xinference/core/supervisor.py
- xinference/core/worker.py
- xinference/web/ui/src/scenes/launch_model/launchLLM.js
- xinference/web/ui/src/scenes/launch_model/modelCard.js
> ENH: [UI] Supports `n_gpu` config when launching LLM models on web ui

- xinference/web/ui/src/scenes/launch_model/embeddingCard.js
- xinference/web/ui/src/scenes/launch_model/modelCard.js
- xinference/web/ui/src/scenes/launch_model/rerankCard.js
- xinference/web/ui/src/scenes/running_models/index.js
> ENH: [UI] Supports `model_uid` input when launching models

- .pre-commit-config.yaml
- xinference/api/restful_api.py
- xinference/core/chat_interface.py
- xinference/core/supervisor.py
- xinference/deploy/utils.py
- xinference/model/embedding/__init__.py
- xinference/model/embedding/core.py
- xinference/model/llm/ggml/chatglm.py
- xinference/model/llm/llm_family.py
- xinference/model/llm/pytorch/core.py
- xinference/model/llm/tests/test_llm_family.py
- xinference/model/rerank/__init__.py
- xinference/model/rerank/core.py
- xinference/model/utils.py
- xinference/web/ui/src/scenes/launch_model/embeddingCard.js
- xinference/web/ui/src/scenes/launch_model/index.js
- xinference/web/ui/src/scenes/launch_model/launchCustom.js
- xinference/web/ui/src/scenes/launch_model/launchEmbedding.js
- xinference/web/ui/src/scenes/launch_model/launchLLM.js
- xinference/web/ui/src/scenes/launch_model/launchRerank.js
- xinference/web/ui/src/scenes/launch_model/rerankCard.js
- xinference/web/ui/src/scenes/register_model/index.js
- xinference/web/ui/src/scenes/running_models/index.js
1. Fix running model padding issue
2. Show cached on embedding and rerank models
3. Fix custom model launching issue
4. Fix cached on LLM models.
5. Fix prompt style issue when registering models
> BUG: Fix `cached` tag on UI

- xinference/model/llm/vllm/core.py
> BUG: Fix stream arg for vllm backend

- xinference/api/restful_api.py
- xinference/core/tests/test_restful_api.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/pytorch/core.py
- xinference/model/llm/utils.py
- This PR does not support qwen ggml.
> FEAT: qwen function call

- xinference/core/tests/test_restful_api.py
- xinference/model/llm/utils.py
If tool call failed, we return a message with a content string and am empty tool_calls list.
> ENH: Handle tool call failed

- examples/FunctionCall.ipynb
Update availabe tool calls models.
> DOC: Update FunctionCall.ipynb

- doc/source/models/sources/sources.rst
- setup.cfg
- xinference/deploy/__init__.py
- xinference/model/llm/vllm/core.py
import modelscope lead to some strange errors when initialize cuda, remove it as the log issues have been solevd.
> BUG: Remove the modelscope import 

- xinference/model/llm/utils.py
- xinference/model/llm/vllm/core.py
Fixes: https://github.com/xorbitsai/inference/issues/781
> ENH: vllm backend support tool calls

- xinference/api/restful_api.py
- xinference/core/tests/test_restful_api.py
- xinference/model/llm/ggml/chatglm.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family.py
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/pytorch/chatglm.py
- xinference/model/llm/tests/test_llm_family.py
- xinference/model/llm/utils.py
- xinference/types.py
The following models can handle tool messages:
- ChatGLM3
- qwen-chat
Fixes: https://github.com/xorbitsai/inference/issues/780
> FEAT: Support tool message

- xinference/core/supervisor.py
- xinference/core/worker.py
- xinference/model/embedding/custom.py
- xinference/model/llm/llm_family.py
> BUG: Xinference does not release custom model name when registering failed

- xinference/model/embedding/custom.py
- xinference/web/ui/src/scenes/register_model/index.js
- xinference/web/ui/src/scenes/register_model/register_embedding.js
> ENH: [UI] register custom embedding model

- xinference/core/worker.py
- xinference/model/llm/tests/test_llm_family.py
> BUG: Worker starts failed on windows

- xinference/model/llm/pytorch/core.py
Custom model name capitalization judgment
> BUG: Find correct class for customized model

- xinference/core/supervisor.py
- xinference/core/worker.py
- xinference/model/rerank/__init__.py
- xinference/model/rerank/core.py
- xinference/model/rerank/custom.py
- xinference/model/rerank/tests/test_rerank.py
- xinference/web/ui/src/scenes/launch_model/launchCustom.js
- xinference/web/ui/src/scenes/launch_model/launchRerank.js
- xinference/web/ui/src/scenes/launch_model/rerankCard.js
- xinference/web/ui/src/scenes/register_model/index.js
- xinference/web/ui/src/scenes/register_model/register_rerank.js
> FEAT: Supports registering rerank models

- examples/Xinference_Quick_Start.ipynb
> BUG: Fix typing_extension version problem in notebook

- setup.cfg
- xinference/deploy/cmdline.py
Fixes: https://github.com/xorbitsai/inference/issues/849
> BUG: Fix multimodal cmdline

- .dockerignore
- .github/workflows/docker-cd.yaml
- doc/source/getting_started/index.rst
- doc/source/getting_started/using_docker_image.rst
- xinference/deploy/docker/Dockerfile
Tested in my forked repo: https://github.com/ChengjieLi28/inference/actions/runs/7395710082/job/20119398509
> BLD: Docker image

- .github/workflows/python.yaml
- setup.cfg
- xinference/api/restful_api.py
- xinference/client/oscar/actor_client.py
- xinference/client/tests/test_client.py
- xinference/core/model.py
Required: https://github.com/xorbitsai/xoscar/pull/83
> ENH: Stream use xoscar generator

- doc/source/user_guide/client_api.rst
- xinference/api/restful_api.py
- Fix create images with empty kwargs.
> DOC: Add OpenAI Client API doc

- docker-compose.yml
> FEAT: docker compose support

- xinference/core/worker.py
Fixes: https://github.com/xorbitsai/inference/issues/884
> BUG: Fix auto recover kwargs

- xinference/deploy/docker/Dockerfile
This reverts commit 1ba2ef77e77fe48147fb9d80d2801b3db1a61a71.
> BUG: Revert #883

- xinference/core/supervisor.py
- xinference/model/llm/__init__.py
- xinference/model/llm/ggml/llamacpp.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family.py
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/pytorch/chatglm.py
- xinference/model/llm/pytorch/core.py
- xinference/model/llm/utils.py
- xinference/model/llm/vllm/core.py
Fixes: https://github.com/xorbitsai/inference/issues/897
> BUG: Fix tool calls on custom model

- xinference/model/multimodal/__init__.py
- xinference/model/multimodal/model_spec_modelscope.json
Fixes: https://github.com/xorbitsai/inference/issues/894
> ENH: qwen vl modelscope

- doc/source/models/builtin/embedding/index.rst
- doc/source/models/builtin/embedding/jina-embeddings-v2-base-zh.rst
- xinference/model/embedding/model_spec.json
- xinference/model/embedding/model_spec_modelscope.json
> FEAT: Support jina-embeddings-v2-base-zh

- doc/source/models/builtin/llm/index.rst
- doc/source/models/builtin/llm/internlm2-chat.rst
- doc/source/models/builtin/llm/mixtral-instruct-v0.1.rst
- doc/source/models/builtin/llm/orion-chat-rag.rst
- doc/source/models/builtin/llm/orion-chat.rst
- doc/source/models/builtin/llm/qwen-vl-chat.rst
- doc/source/models/builtin/llm/yi-vl-chat.rst
- setup.cfg
- xinference/model/llm/__init__.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/pytorch/core.py
- xinference/model/llm/pytorch/yi_vl.py
- xinference/model/llm/tests/test_multimodal.py
- xinference/thirdparty/llava/__init__.py
- xinference/thirdparty/llava/conversation.py
- xinference/thirdparty/llava/mm_utils.py
- xinference/thirdparty/llava/model/__init__.py
- xinference/thirdparty/llava/model/clip_encoder/builder.py
- xinference/thirdparty/llava/model/clip_encoder/clip_encoder.py
- xinference/thirdparty/llava/model/constants.py
- xinference/thirdparty/llava/model/llava_arch.py
- xinference/thirdparty/llava/model/llava_llama.py
- xinference/thirdparty/llava/model/multimodal_projector/builder.py
- Currenly, only non stream mode is implemented.
> FEAT: Support Yi VL

- .github/workflows/python.yaml
- doc/source/models/builtin/embedding/bce-embedding-base_v1.rst
- doc/source/models/builtin/embedding/bge-m3.rst
- doc/source/models/builtin/embedding/index.rst
- doc/source/models/builtin/rerank/bce-reranker-base_v1.rst
- doc/source/models/builtin/rerank/index.rst
- setup.cfg
- xinference/model/embedding/model_spec.json
- xinference/model/embedding/model_spec_modelscope.json
- xinference/model/rerank/model_spec.json
- xinference/model/rerank/model_spec_modelscope.json
> FEAT: Support more embedding and rerank models

- xinference/api/restful_api.py
- xinference/core/tests/test_restful_api.py
- xinference/core/tests/test_types.py
- xinference/model/llm/pytorch/utils.py
- xinference/types.py
> ENH: Allow chat max_tokens is None

- README.md
- README_zh_CN.md
> DOC: Update README.md

- doc/source/models/builtin/rerank/index.rst
- doc/source/user_guide/index.rst
- doc/source/user_guide/metrics.rst
- doc/templates/metrics.jinja
- doc/templates/rerank_index.rst.jinja
- xinference/api/restful_api.py
- Use model family instead of checking model name.
Fixes: https://github.com/xorbitsai/inference/issues/976
> BUG: Fix custom model tool calls

- setup.cfg
- xinference/_compat.py
- xinference/api/oauth2/auth_service.py
- xinference/api/oauth2/types.py
- xinference/api/restful_api.py
- xinference/core/status_guard.py
- xinference/core/tests/test_restful_api.py
- xinference/core/tests/test_types.py
- xinference/core/utils.py
- xinference/fields.py
- xinference/model/audio/core.py
- xinference/model/embedding/core.py
- xinference/model/image/core.py
- xinference/model/llm/llm_family.py
- xinference/model/rerank/core.py
- xinference/types.py
> REF: Supports `pydantic` v2

- xinference/model/core.py
- xinference/model/embedding/core.py
- xinference/model/embedding/tests/test_embedding_models.py
- xinference/model/image/__init__.py
- xinference/model/image/core.py
- xinference/model/image/model_spec_modelscope.json
- xinference/model/rerank/core.py
- xinference/model/rerank/tests/test_rerank.py
- xinference/model/utils.py
- Fix model cache is not reused.
> ENH: Download stable diffusion model from modelscope

- xinference/api/restful_api.py
`body.messages` is a list_iterator returned by pydantic, so we need to convert it to a list before indexing it.
Fix #1004
> BUG: fix chat completion error when indexing body.messages

- xinference/web/ui/src/scenes/launch_model/modelCard.js
> ENH: [UI] Supports `replica` when launching LLM models

- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
Fixes: https://github.com/xorbitsai/inference/issues/1021
> BUG: Fix missing qwen 1.5 7b gguf

- xinference/client/restful/restful_client.py
> ENH: Restful client supports multiple system prompts for chat

- doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
- doc/source/user_guide/backends.rst
- xinference/deploy/cmdline.py
- xinference/deploy/utils.py
> ENH: Extra params for `xinference launch` command line

- .github/workflows/docker-cd.yaml
- xinference/deploy/docker/cpu.Dockerfile
Tested on my forked repo: https://github.com/ChengjieLi28/inference/actions/runs/8106603607
> FEAT: Docker for cpu only

- xinference/model/llm/ggml/llamacpp.py
Fixes #999 
Example:
```
xinference launch -e http://127.0.0.1:12306 -n qwen1.5-chat -t LLM -s 4 -f ggufv2 -q q4_0 --n_gpu_layers 0
```
> ENH: Supports `n_gpu_layers` parameter for `llama-cpp-python`

- xinference/device_utils.py
- xinference/web/ui/src/scenes/launch_model/modelCard.js
> ENH: [UI] Support setting `CPU` when selecting n_gpu

- xinference/core/supervisor.py
> BUG: fix the useless fstring.

- xinference/deploy/cmdline.py
> BUG: Fix missing information for `xinference registrations` and `xinference list` command

- xinference/api/restful_api.py
> BUG: Fix cannot continue to chat after canceling the streaming chat via `ctrl+c`

- xinference/api/restful_api.py
- xinference/core/tests/test_restful_api.py
- xinference/model/llm/pytorch/chatglm.py
- xinference/model/llm/pytorch/internlm2.py
- xinference/model/llm/utils.py
Fixes #1143 
Fixes #1113
Fixes #1158
> BUG: Fix OpenAI compatibility issue during chat

- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/utils.py
> FEAT: Support CodeShell model

- xinference/model/llm/vllm/core.py
Added vllm support for deepseek models，including deepseek-chat, deepseek-coder-instruct
> Added vllm support for deepseek models

- .pre-commit-config.yaml
- doc/source/models/builtin/llm/aquila2-chat-16k.rst
- doc/source/models/builtin/llm/aquila2-chat.rst
- doc/source/models/builtin/llm/aquila2.rst
- doc/source/models/builtin/llm/chatglm3-128k.rst
- doc/source/models/builtin/llm/gorilla-openfunctions-v2.rst
- doc/source/models/builtin/llm/index.rst
- doc/source/models/builtin/llm/minicpm-2b-dpo-bf16.rst
- doc/source/models/builtin/llm/minicpm-2b-dpo-fp16.rst
- doc/source/models/builtin/llm/minicpm-2b-dpo-fp32.rst
- doc/source/models/builtin/llm/minicpm-2b-sft-bf16.rst
- doc/source/models/builtin/llm/minicpm-2b-sft-fp32.rst
- doc/source/models/builtin/llm/platypus2-70b-instruct.rst
- setup.cfg
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/utils.py
Fixes #384 
Fixes #537 
Fixes #1116 
Fixes #1187 
Fixes #973
> FEAT: support some builtin new models

- xinference/deploy/docker/Dockerfile
- xinference/deploy/docker/cpu.Dockerfile
> BUG: Fix cannot start xinference in docker due to `cv2`

- setup.cfg
- xinference/deploy/docker/Dockerfile
- xinference/deploy/docker/cpu.Dockerfile
> BUG: Fix `opencv` issue in docker container

- .github/workflows/python.yaml
- setup.cfg
- xinference/deploy/docker/cpu.Dockerfile
See https://github.com/abetlen/llama-cpp-python/issues/1319
> TST: Fix tests due to `llama-cpp-python` `v0.2.58`

- xinference/web/ui/src/scenes/launch_model/index.js
> BUG: style spell error

- doc/source/getting_started/installation.rst
- doc/source/user_guide/backends.rst
- xinference/model/llm/pytorch/chatglm.py
- xinference/model/llm/pytorch/internlm2.py
- xinference/model/llm/vllm/core.py
Fixes #1095 
The system prompt will be ignored for pytorch not for vllm.
> BUG: fix system prompts for chatglm3 and internlm2 pytorch

- xinference/web/ui/src/scenes/launch_model/modelCard.js
- xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.js
https://github.com/xorbitsai/inference/assets/918617/75163c83-e21f-4b71-85a7-54013d323dac
> ENH: UI: paper material for cards

- .github/workflows/python.yaml
- setup.cfg
- xinference/model/rerank/core.py
- xinference/model/rerank/model_spec.json
- xinference/model/rerank/model_spec_modelscope.json
- xinference/model/rerank/tests/test_rerank.py
Fixes: https://github.com/xorbitsai/inference/issues/1265
> FEAT: Support BAAI/bge-reranker-v2-* rerank model

- doc/source/getting_started/installation.rst
- doc/source/models/builtin/embedding/index.rst
- doc/source/models/builtin/embedding/m3e-base.rst
- doc/source/models/builtin/embedding/m3e-large.rst
- doc/source/models/builtin/embedding/m3e-small.rst
- doc/source/models/builtin/llm/codeqwen1.5-chat.rst
- doc/source/models/builtin/llm/index.rst
- doc/source/user_guide/backends.rst
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/vllm/core.py
> FEAT: support codeqwen1.5-chat

- xinference/deploy/cmdline.py
> BUG: Fix Launching embedding or reranking models from commandline fails due to PEFT 

- xinference/model/audio/model_spec.json
Fixes: https://github.com/xorbitsai/inference/issues/1337
> FEAT: Add Belle-whisper-large-v3-zh

- xinference/core/worker.py
> BUG: Fix extra parameters issue when auto-recovering models

- xinference/model/embedding/core.py
- xinference/model/rerank/core.py
- Support `XINFERENCE_EMBEDDING_EMPTY_CACHE_COUNT`, default 10
- Support `XINFERENCE_RERANK_EMPTY_CACHE_COUNT`, default 10
> ENH: Clear cache for embedding and rerank

- xinference/model/llm/llm_family.json
Fix of the file name for andrewcanis/c4ai-command-r-v01-GGUF.
> BUG: fix file template of andrewcanis/c4ai-command-r-v01-GGUF

- doc/source/models/builtin/llm/index.rst
- doc/source/models/builtin/llm/phi-3-mini-128k-instruct.rst
- doc/source/models/builtin/llm/phi-3-mini-4k-instruct.rst
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/utils.py
Resolve #1371
Add phi-3-mini-128k-instruct and phi-3-mini-4k-instruct.
> feat: add phi-3-mini series

- xinference/core/tests/test_restful_api.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- Update model version.
- Add ut.
> ENH: Update chatglm3 6b model version

- .github/workflows/docker-cd.yaml
See https://github.com/xorbitsai/inference/actions/runs/8872625046/job/24357238245
> BLD: Use self-hosted aws machine to build docker image

- xinference/core/tests/test_restful_api.py
- xinference/model/llm/utils.py
Fixes: https://github.com/xorbitsai/inference/issues/1293
> BUG: Fix qwen tool call paramerter empty issue

- xinference/core/model.py
- xinference/core/tests/test_metrics.py
> BUG：Fix mertics is empty when call `/v1/chat/completions`

- xinference/core/tests/test_restful_api.py
- xinference/model/llm/utils.py
The qwen model use ReAct to call tools, the token usage may larger than the expected.
- Fixes: https://github.com/xorbitsai/inference/issues/1412
> BUG: Fix tool calls return invalid usage

- .github/workflows/python.yaml
- xinference/api/restful_api.py
- xinference/client/restful/restful_client.py
- xinference/core/model.py
- xinference/model/audio/tests/test_whisper.py
- xinference/model/audio/whisper.py
- Fix temperature not set.
- Fixes: https://github.com/xorbitsai/inference/issues/1387
- Fixes: https://github.com/xorbitsai/inference/issues/1253
> FEAT: Audio support verbose_json and timestamp

- xinference/core/worker.py
- xinference/model/llm/core.py
1. Catch and ignore network exception 
2. Remove unused function
> ENH: Some minor changes

- setup.cfg
> BUG: Install error on MacOS due to `auto-gptq`

- README.md
- README_zh_CN.md
> DOC: Update readme for being integrated by RAGFlow

- xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
- xinference/web/ui/src/scenes/launch_model/index.js
- xinference/web/ui/src/scenes/launch_model/modelCard.js
> FEAT: [UI] embedding and rerank support the specified GPU and CPU.

- xinference/deploy/docker/Dockerfile
Docker image may crash in some envs due to llama.cpp compilation in dockerfile
See related issue https://github.com/ggerganov/llama.cpp/issues/1027
So try to use pre-built whl package to fix this.
Fixes #1499
> BUG: Docker image crash during startup due to `llama-cpp-python`

- benchmark/benchmark_rerank.py
Implement a stress test for rerank.
> CHORE: Basic benchmark/benchmark_rerank.py

- doc/source/development/xinference_internals.rst
- doc/source/locale/zh_CN/LC_MESSAGES/development/xinference_internals.po
- xinference/thirdparty/deepseek_vl/models/processing_vlm.py
- xinference/thirdparty/deepseek_vl/models/siglip_vit.py
- xinference/thirdparty/deepseek_vl/serve/app_deepseek.py
- xinference/thirdparty/deepseek_vl/serve/app_modules/utils.py
- xinference/thirdparty/deepseek_vl/serve/assets/custom.css
- xinference/thirdparty/llava/mm_utils.py
- xinference/thirdparty/llava/model/llava_arch.py
Some changes about thirdparty code and doc when running `pre-commit run -a`
> BLD: Fix pre commit

- doc/source/getting_started/installation.rst
- doc/source/models/builtin/llm/deepseek-coder.rst
- doc/source/models/builtin/llm/deepseek.rst
- doc/source/models/builtin/llm/index.rst
- doc/source/user_guide/backends.rst
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/vllm/core.py
Deepseek llm and coder base is absent, but coder base is useful for code complete.
> FEAT: add deepseek llm and coder base

- doc/source/getting_started/installation.rst
- doc/source/models/builtin/llm/codeqwen1.5.rst
- doc/source/models/builtin/llm/index.rst
- doc/source/user_guide/backends.rst
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/vllm/core.py
Base model is useful for code completion job, thus added codeqwen1.5 base model.
> FEAT: add codeqwen1.5

- setup.cfg
- xinference/deploy/docker/cpu.Dockerfile
- xinference/thirdparty/omnilmm/chat.py
Main reason is thirdparty of OmniLLM inited cuda in some imports, but I don't know what triggered, so I move the imports into functions.
> BLD: compatible with torch 2.3.0

- xinference/model/rerank/core.py
- xinference/model/rerank/tests/test_rerank.py
Auto detect rerank type based on the tokenizer name.
Fixes: https://github.com/xorbitsai/inference/issues/1515
> FEAT: Auto detect rerank type for unknown rerank type

- xinference/model/llm/__init__.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/pytorch/core.py
- xinference/model/llm/pytorch/intern_vl.py
include：
Intern-VL-Chat-1.5
Intern-VL-Chat-1.5-Int8
Mini-Intern-VL-Chat-1.5
> ENH: Support Intern-VL-Chat model

- README.md
- README_zh_CN.md
- doc/source/gen_docs.py
- doc/source/getting_started/installation.rst
- doc/source/models/builtin/llm/index.rst
- doc/source/models/builtin/llm/starling-lm.rst
- doc/source/models/builtin/llm/yi-1.5-chat-16k.rst
- doc/source/models/builtin/llm/yi-1.5-chat.rst
- doc/source/user_guide/backends.rst
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/vllm/core.py
This PR added more formats for Yi-1.5-chat, and added Yi-1.5-chat-16k
> FEAT: support Yi-1.5-chat-16k

- xinference/core/chat_interface.py
- xinference/model/llm/pytorch/intern_vl.py
> ENH: add additional_option at vl gradio

- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/pytorch/cogvlm2.py
https://github.com/xorbitsai/inference/assets/918617/7055f715-94ff-41a5-9d08-a6aa60c87091
> ENH: make CogVLM2 support stream output

- .github/workflows/python.yaml
- doc/source/models/builtin/audio/chattts.rst
- doc/source/models/builtin/audio/index.rst
- doc/templates/audio.rst.jinja
- pyproject.toml
- setup.cfg
- xinference/api/restful_api.py
- xinference/client/restful/restful_client.py
- xinference/core/model.py
- xinference/model/audio/chattts.py
- xinference/model/audio/core.py
- xinference/model/audio/model_spec.json
- xinference/model/audio/tests/test_chattts.py
- xinference/thirdparty/ChatTTS/__init__.py
- xinference/thirdparty/ChatTTS/core.py
- xinference/thirdparty/ChatTTS/experimental/llm.py
- xinference/thirdparty/ChatTTS/infer/api.py
- xinference/thirdparty/ChatTTS/model/dvae.py
- xinference/thirdparty/ChatTTS/model/gpt.py
- xinference/thirdparty/ChatTTS/utils/gpu_utils.py
- xinference/thirdparty/ChatTTS/utils/infer_utils.py
- xinference/thirdparty/ChatTTS/utils/io_utils.py
- Basic support `speech` audio API
- Compatible with OpenAI speech API
- Support ChatTTS
- Fixes: https://github.com/xorbitsai/inference/issues/1288
> FEAT: Support ChatTTS

- doc/source/getting_started/installation.rst
- doc/source/reference/index.rst
- doc/source/user_guide/backends.rst
- xinference/client/restful/restful_client.py
> DOC: Fix audio doc

- xinference/model/llm/__init__.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/pytorch/core.py
- xinference/model/llm/pytorch/glm4v.py
https://github.com/xorbitsai/inference/assets/918617/ef0cab6d-6a94-4a6d-b997-243d58e30720
> Feat: support glm-4v 9b

- xinference/model/utils.py
> BUG: fix XINFERENCE_MODEL_SRC behavior

- xinference/core/model.py
- xinference/core/scheduler.py
- xinference/model/llm/pytorch/core.py
- xinference/model/llm/pytorch/qwen_vl.py
- xinference/model/llm/pytorch/utils.py
1. Support `generate` interface for continuous batching
2. Fix streaming chunk id issue. All the chunk id should be same
See: https://platform.openai.com/docs/api-reference/chat/streaming
> ENH: Supports `generate` interface for continuous batching

- xinference/api/restful_api.py
- xinference/core/tests/test_restful_api.py
- xinference/model/llm/utils.py
Qwen2 is not on the whitelist for function calls. Add it to support function calls.
> FEAT: qwen2-instruct support tool call

- xinference/api/restful_api.py
- xinference/core/tests/test_restful_api.py
- xinference/model/llm/pytorch/chatglm.py
- xinference/model/llm/utils.py
Fixes: https://github.com/xorbitsai/inference/issues/1592 https://github.com/xorbitsai/inference/issues/1630
> FEAT: glm4-chat support tool call

- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/pytorch/glm4v.py
> ENH: quantization for glm-4v

- xinference/model/llm/pytorch/glm4v.py
> BUG: show error when user launch quantized model without device supported

- xinference/model/rerank/core.py
Fixes: https://github.com/xorbitsai/inference/issues/1635
> BUG: Fix default rerank type

- xinference/api/restful_api.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/utils.py
This PR adds tools support for the Qwen series Mixture of Experts (MOE) models. The Qwen Chat series MOE models possess similar tool call capabilities as other dense models, enhancing their utility and consistency.
> FEAT: Add Tools Support for Qwen Series MOE Models

- .github/workflows/python.yaml
See https://github.com/run-llama/llama_index/issues/14190
> TST: Fix CI due to `tenacity`

- xinference/web/ui/src/components/deleteDialog.js
- xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
- xinference/web/ui/src/scenes/launch_model/launchCustom.js
- xinference/web/ui/src/scenes/launch_model/launchLLM.js
- xinference/web/ui/src/scenes/launch_model/modelCard.js
> FEAT: [UI]Modify the deletion function of a custom model.

- .pre-commit-config.yaml
prevent `pre-commit run -a` change xinference/thirdparty/
> CHORE: [pre-commit] Add exclude thirdparty rules

- xinference/web/ui/src/components/MenuSide.js
- xinference/web/ui/src/components/copyComponent/copyComponent.js
- xinference/web/ui/src/components/copyComponent/style.css
- xinference/web/ui/src/components/deleteDialog.js
- xinference/web/ui/src/router/index.js
- xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
- xinference/web/ui/src/scenes/launch_model/launchLLM.js
- xinference/web/ui/src/scenes/launch_model/modelCard.js
- xinference/web/ui/src/scenes/launch_model/styles/launchModelStyle.js
- xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.css
- xinference/web/ui/src/scenes/register_model/components/addControlnet.js
- xinference/web/ui/src/scenes/register_model/components/addModelSpecs.js
- xinference/web/ui/src/scenes/register_model/index.js
- xinference/web/ui/src/scenes/register_model/registerModel.js
- xinference/web/ui/src/scenes/register_model/styles/registerModelStyle.css
> FEAT: [UI]Custom model presents JSON data and modifies it.

- xinference/deploy/docker/Dockerfile
See https://github.com/li-plus/chatglm.cpp/releases
> BLD: pin `chatglm-cpp` version `v0.3.x`

- xinference/deploy/docker/Dockerfile
1. make sure `llama-cpp-python` installed from prebuilt channel
2. downgrade`chatglm-cpp` to `v0.3.x`
Fixes #1704
> BUG: GGUF models cannot use GPU in docker

- xinference/api/restful_api.py
- xinference/core/tests/test_restful_api.py
- xinference/model/llm/ggml/llamacpp.py
- xinference/model/llm/pytorch/chatglm.py
- xinference/model/llm/pytorch/core.py
- xinference/model/llm/utils.py
- xinference/model/llm/vllm/core.py
Fixes: https://github.com/xorbitsai/inference/issues/1644
Fixes: https://github.com/xorbitsai/inference/issues/1709
> BUG: Fix tool call observation

- xinference/core/model.py
> BUG: curl with stream returns unicode chars rather than chinese character

- xinference/web/package-lock.json
- xinference/web/ui/package-lock.json
see bellow changes
name | version | CNNVD | CVE | fixed version
-- | -- | -- | -- | --
micromatch | 4.0.5 | CNNVD-202405-2275 | CVE-2024-4067 | 4.0.6
braces | 3.0.2 | CNNVD-202405-2274 | CVE-2024-4068 | 3.0.3
webpack-dev-middleware | 5.3.3 | CNNVD-202403-2183 | CVE-2024-29180 | 5.3.4
> CHORE: upgrade version fix security vulnerability

- xinference/api/restful_api.py
- xinference/conftest.py
- xinference/core/tests/test_restful_api.py
- xinference/web/ui/src/scenes/cluster_info/nodeInfo.js
- xinference/web/ui/src/scenes/launch_model/index.js
> BUG: Cluster info can be accessed without authorization in the auth mode

- .github/workflows/docker-cd.yaml
Tested: https://github.com/xorbitsai/inference/actions/runs/9740420675/job/26877501428
> BLD: Supports Aliyun docker image

- xinference/deploy/docker/Dockerfile
- xinference/deploy/docker/requirements.txt
Reduce docker image size from ~13GB to ~6GB
> BLD: GPU docker use `vllm` image as base

- xinference/web/ui/src/App.js
- xinference/web/ui/src/components/MenuSide.js
- xinference/web/ui/src/components/Title.js
- xinference/web/ui/src/components/apiContext.js
- xinference/web/ui/src/components/fetchWrapper.js
- xinference/web/ui/src/router/index.js
- xinference/web/ui/src/scenes/cluster_info/index.js
- xinference/web/ui/src/scenes/cluster_info/nodeInfo.js
- xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
- xinference/web/ui/src/scenes/launch_model/index.js
- xinference/web/ui/src/scenes/launch_model/launchCustom.js
- xinference/web/ui/src/scenes/launch_model/launchLLM.js
- xinference/web/ui/src/scenes/launch_model/modelCard.js
- xinference/web/ui/src/scenes/register_model/index.js
- xinference/web/ui/src/scenes/register_model/registerModel.js
- xinference/web/ui/src/scenes/running_models/index.js
> BUG: [UI] Fix authentication mode related bugs

- xinference/model/rerank/core.py
Fixes: https://github.com/xorbitsai/inference/issues/1775
> BUG: Fix LLM based reranker may raise a TypeError

- xinference/thirdparty/deepseek_vl/serve/__init__.py
- xinference/thirdparty/deepseek_vl/serve/app_modules/__init__.py
> BUG: fix deepseek-vl-chat

- doc/source/locale/ja_JP/LC_MESSAGES/models/custom.po
- doc/source/locale/zh_CN/LC_MESSAGES/models/custom.po
- doc/source/models/custom.rst
> DOC: Define a custom Rerank model

- .github/workflows/issue.yaml
See https://docs.github.com/zh/actions/managing-issues-and-pull-requests/closing-inactive-issues
> CHORE: Close issue when it is stale

- xinference/model/llm/llm_family.py
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/utils.py
- xinference/web/ui/src/scenes/launch_model/launchLLM.js
- xinference/web/ui/src/scenes/launch_model/modelCard.js
> BUG: cache status missing for model id with quantization placeholder

- xinference/core/model.py
> BUG: Fix stream unicode issue for chinese characters when using vllm backend

- xinference/model/llm/sglang/core.py
https://github.com/xorbitsai/inference/issues/1869
> BUG: sglang stream error while stream_option not set

- xinference/web/ui/src/scenes/launch_model/modelCard.js
> FEAT: [UI]Add configuration for image and audio models.

- doc/source/getting_started/installation.rst
- doc/source/models/builtin/llm/llama-3.1-instruct.rst
- doc/source/user_guide/backends.rst
- setup.cfg
- xinference/model/llm/vllm/core.py
> Feat: support for llama 3.1 for vllm

- xinference/model/llm/sglang/core.py
Test llama3  with our environment.
> ENH: Add support of sglang for llama 3 qwen 2

- xinference/model/llm/pytorch/chatglm.py
- Fix GLM chat non stream chat without tool.
Fixes #1960 .
> BUG: Fix GLM chat

- xinference/deploy/docker/Dockerfile
Fixes #1949 
Fixes #1971 
Fixes #1959
> BUG: Load llama.so failed in docker image

- benchmark/benchmark_latency.py
- benchmark/benchmark_long.py
- benchmark/benchmark_rerank.py
- benchmark/benchmark_serving.py
- benchmark/utils.py
Support passing api key to benchmark script.
> ENH: [benchmark] Add api-key support

- doc/source/getting_started/installation.rst
- doc/source/getting_started/installation_npu.rst
- doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
- doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation_npu.po
- doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
- doc/source/user_guide/backends.rst
Added ascend NPU doc.
Fixes #1689 .
> DOC: ascend support

- xinference/web/ui/src/scenes/launch_model/modelCard.js
> BUG: [UI]Modifying 'model format' again resulted in an error message.

- xinference/api/restful_api.py
- xinference/client/restful/restful_client.py
- xinference/core/image_interface.py
- xinference/core/model.py
- xinference/model/image/core.py
- xinference/model/image/model_spec.json
- xinference/model/image/model_spec_modelscope.json
- xinference/model/image/stable_diffusion/core.py
- xinference/model/image/tests/test_stable_diffusion.py
Before image_to_image requires controlnet, but many sd models is able to image_to_image, thus add the ability to those models.
> ENH: support image_to_image

- doc/source/models/model_abilities/audio.rst
- xinference/api/restful_api.py
For 500 internal server error:
- Response error string.
- Log error traceback.
Fix doc.
Fixes: https://github.com/xorbitsai/inference/issues/1995
> ENH: Improve internal server error

- .github/workflows/python.yaml
- doc/source/models/builtin/audio/index.rst
- doc/source/models/builtin/audio/sensevoicesmall.rst
- doc/source/models/model_abilities/audio.rst
- setup.cfg
- xinference/deploy/docker/requirements.txt
- xinference/deploy/docker/requirements_cpu.txt
- xinference/model/audio/core.py
- xinference/model/audio/funasr.py
- xinference/model/audio/model_spec.json
- xinference/model/audio/model_spec_modelscope.json
- xinference/model/audio/tests/test_funasr.py
- xinference/model/audio/whisper.py
This PR introduced SenseVoiceSmall audio-to-text model, and FunASR is introduced as well, in the future, we can include more FunASR models.
Fixes #1802 
Fixes #1071
> FEAT: support SenseVoice audio-to-text model

- setup.cfg
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
Add support for llama-3.1-instruct 405B model
> FEAT: Add support for llama-3.1-instruct 405B model

- doc/source/locale/ja_JP/LC_MESSAGES/reference/index.po
- doc/source/locale/zh_CN/LC_MESSAGES/reference/index.po
- doc/source/reference/index.rst
- xinference/client/handlers.py
- xinference/client/restful/restful_client.py
- xinference/core/chat_interface.py
- xinference/deploy/cmdline.py
- xinference/deploy/docker/cpu.Dockerfile
- xinference/types.py
> REF: Mark `Deprecate` for `prompt`, `system_prompt` and `chat_history` parameters in `chat` client interface

- README.md
> DOC: fix typo in README

- xinference/api/restful_api.py
- xinference/core/tests/test_restful_api.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/pytorch/chatglm.py
- xinference/model/llm/utils.py
- Fix custom glm4 issue.
- Update glm4 hf to the latest, compatible with transformers 4.44
- Disable tool call for glm3.
Fixes: https://github.com/xorbitsai/inference/issues/2074 
Fixes: https://github.com/xorbitsai/inference/issues/2055
> BUG: Fix custom glm4 & remove tool calls of ChatGLM3

- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family.py
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/sglang/core.py
- xinference/model/llm/utils.py
- xinference/model/llm/vllm/core.py
- xinference/web/ui/src/scenes/register_model/components/addModelSpecs.js
> FEAT: support FP8 for vllm & sglang engine

- xinference/web/ui/src/scenes/launch_model/modelCard.js
> FEAT: [UI] Add other parameters to other models besides the LLM model.

- xinference/core/chat_interface.py
- xinference/model/llm/transformers/intern_vl.py
https://github.com/user-attachments/assets/0c19355d-4f44-4cd4-a07c-b8e5af434078
> ENH: make internvl2 support video

- doc/source/models/builtin/audio/fishspeech-1.2-sft.rst
- doc/source/models/builtin/audio/index.rst
- doc/source/models/builtin/llm/cogvlm2-video-llama3-chat.rst
- doc/source/models/builtin/llm/index.rst
- xinference/deploy/docker/requirements.txt
- xinference/deploy/docker/requirements_cpu.txt
- Add doc for fish speech
- Add doc for cogvlm2 video
- Add deps for docker.
> DOC: Add doc for fish speech and cogvlm2 video

- xinference/core/worker.py
Mark model status ERROR instead of TERMINATED after model die,
to distinguish with the behavior when model terminated by user.
由于 model die 的时候，先 terminate 再 re-launch,  用 TERMINATED 可能会在语义上与正常模型停止有冲突. 并且假如 model 多次 relaunch 失败放弃重试, 用 termianted 就不会在 supervisor 中留下状态. 所以用 ERROR 更好
> ENH: Fix callback status when model die

- xinference/model/audio/chattts.py
- xinference/model/audio/cosyvoice.py
- xinference/model/audio/tests/test_cosyvoice.py
- xinference/model/utils.py
`cosyvoice-300m-instruct` can accept text without instruction, this PR added the ability.
> ENH: support cosyvoice-300m-instruct without instruction

- setup.cfg
- xinference/deploy/docker/requirements.txt
- xinference/deploy/docker/requirements_cpu.txt
- xinference/thirdparty/fish_speech/tools/api.py
- Fixes: https://github.com/xorbitsai/inference/issues/2158
> ENH: Remove opencc and fast_whisper

- xinference/model/llm/vllm/core.py
solve the problem of health check for image-to-text model
> ENH: solve the problem of health check for image-to-text model

- xinference/model/embedding/core.py
> BUG: 🐛 fix unable launch qwen2-embedding

- xinference/model/llm/sglang/core.py
FIx: https://github.com/xorbitsai/inference/issues/2169
> BUG: configuration key different by sglang's version

- xinference/model/audio/custom.py
- xinference/model/embedding/custom.py
- xinference/model/embedding/tests/test_embedding_models.py
- xinference/model/flexible/core.py
- xinference/model/image/custom.py
- xinference/model/llm/llm_family.py
- xinference/model/rerank/custom.py
- xinference/model/rerank/tests/test_rerank.py
Fix the bug that even if the registration fails, the model is still written to the registration list
> BUG: fix register model list error

- xinference/core/worker.py
- xinference/model/image/tests/test_stable_diffusion.py
- Fixes: https://github.com/xorbitsai/inference/issues/2168
> BUG: Fix list video model

- xinference/model/rerank/core.py
- xinference/model/rerank/model_spec.json
- xinference/model/rerank/model_spec_modelscope.json
- xinference/model/rerank/tests/test_rerank.py
Fixes #1695 .
Fixes #1639 .
Fixes #1398 .
> BUG: fix rerank max length

- xinference/model/llm/utils.py
- xinference/model/utils.py
> Revert "EHN: clean cache for VL models (#2163)"

- xinference/model/audio/cosyvoice.py
- xinference/model/audio/tests/test_cosyvoice.py
- xinference/thirdparty/cosyvoice/bin/export_jit.py
- xinference/thirdparty/cosyvoice/bin/export_trt.py
- xinference/thirdparty/cosyvoice/bin/inference.py
- xinference/thirdparty/cosyvoice/cli/cosyvoice.py
- xinference/thirdparty/cosyvoice/cli/frontend.py
- xinference/thirdparty/cosyvoice/cli/model.py
- xinference/thirdparty/cosyvoice/flow/flow.py
- xinference/thirdparty/cosyvoice/flow/length_regulator.py
- xinference/thirdparty/cosyvoice/hifigan/generator.py
- xinference/thirdparty/cosyvoice/llm/llm.py
- xinference/thirdparty/cosyvoice/transformer/attention.py
- xinference/thirdparty/cosyvoice/transformer/decoder.py
- xinference/thirdparty/cosyvoice/transformer/embedding.py
- xinference/thirdparty/cosyvoice/transformer/encoder.py
- xinference/thirdparty/cosyvoice/utils/common.py
- xinference/thirdparty/cosyvoice/utils/file_utils.py
CosyVoice-300M 和 CosyVoice-300M-Instruct以及CosyVoice-300M-SFT，支持流式输出
> FEAT: cosyvoice model support streaming reply

- doc/source/locale/zh_CN/LC_MESSAGES/user_guide/continuous_batching.po
- doc/source/user_guide/continuous_batching.rst
- xinference/constants.py
- xinference/core/model.py
- xinference/model/llm/transformers/minicpmv26.py
> ENH: `MiniCPM-V-2.6` Supports continuous batching with transformers engine

- xinference/api/restful_api.py
- xinference/core/image_interface.py
- xinference/core/model.py
- xinference/deploy/docker/requirements.txt
- xinference/deploy/docker/requirements_cpu.txt
- xinference/model/audio/fish_speech.py
- xinference/model/image/core.py
- xinference/model/image/model_spec.json
- xinference/model/image/model_spec_modelscope.json
- xinference/model/image/sdapi.py
- xinference/model/image/stable_diffusion/core.py
- xinference/model/image/tests/test_stable_diffusion.py
- xinference/model/llm/transformers/chatglm.py
- xinference/model/llm/utils.py
- xinference/types.py
About sd API, refer to https://github.com/mix1009/sdwebuiapi/blob/main/webuiapi/webuiapi.py
> FEAT: support sdapi/txt2img

- xinference/model/llm/utils.py
Related #2259 
Example for qwen2:
```
tools = [{'type': 'function',
'function': {'name': 'find_sports_shoes',
'description': '查找商场内可用的运动鞋信息',
'parameters': {'type': 'object',
'properties': {'brand': {'type': 'string', 'description': '鞋子的品牌'},
'size': {'type': 'string', 'description': '鞋子的尺码'}},
'required': ['brand']},
'strict': False}},
{'type': 'function',
'function': {'name': 'find_clothes',
'description': '查询商场中可用的风衣信息',
'parameters': {'type': 'object',
'properties': {'brand': {'type': 'string', 'description': '衣服的品牌'},
'size': {'type': 'string', 'description': '衣服的尺码'}},
'required': ['brand']},
'strict': False}}]
model.chat([{"role": "user", "content": "查询鸿星尔克XXXL码的风衣和李宁43码的鞋子"}], tools=tools)
```
Results:
```
{'id': 'chatcmpl-8c105b66-7ae9-458a-8ae3-4cd3dccda075',
'model': …
```
> ENH: Supports multi functions in tool call for qwen2

- xinference/client/restful/restful_client.py
Close:https://github.com/xorbitsai/inference/issues/2269
> BUG: tts stream mode not working

- xinference/model/llm/__init__.py
> BUG: support old register llm format

- xinference/core/model.py
- xinference/model/image/stable_diffusion/core.py
Support calling Flux.1-dev from dify now.
> BUG: fix stable diffusion from dify tool

- setup.cfg
- xinference/client/tests/test_client.py
- xinference/deploy/docker/requirements.txt
- xinference/deploy/docker/requirements_cpu.txt
- xinference/model/embedding/core.py
- xinference/model/embedding/model_spec.json
- xinference/model/embedding/model_spec_modelscope.json
- xinference/model/rerank/core.py
- xinference/model/utils.py
> Feat: Support jina-embedding-v3

- xinference/model/audio/model_spec.json
- xinference/model/audio/model_spec_modelscope.json
1.add whisper-large-v3-turbo audio model
> FEAT: add whisper-large-v3-turbo audio model

- xinference/model/llm/utils.py
> BUG: tool call streaming output has duplicated list

- xinference/model/audio/chattts.py
- xinference/model/audio/tests/test_chattts.py
The kwargs will be passed to `ChatTTS.Chat.load`
> ENH: Launch the ChatTTS model with kwargs

- xinference/model/llm/vllm/core.py
This feature is tested on qwen2-vl.
> FEAT: Adding support for awq/gptq inference to VisionModel such as Qwen2-VL

- doc/source/models/builtin/llm/qwen2.5-instruct.rst
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/web/ui/src/scenes/register_model/components/addModelSpecs.js
> FEAT: added MLX for qwen2.5-instruct

- setup.cfg
- xinference/core/chat_interface.py
- xinference/core/image_interface.py
- xinference/core/scheduler.py
- xinference/deploy/docker/requirements.txt
- xinference/deploy/docker/requirements_cpu.txt
- xinference/model/image/core.py
- xinference/model/image/model_spec.json
- xinference/model/image/model_spec_modelscope.json
- xinference/model/image/scheduler/flux.py
- xinference/model/image/stable_diffusion/core.py
- xinference/model/image/stable_diffusion/mlx.py
- xinference/thirdparty/mlx/__init__.py
- xinference/thirdparty/mlx/flux/__init__.py
- xinference/thirdparty/mlx/flux/autoencoder.py
- xinference/thirdparty/mlx/flux/clip.py
- xinference/thirdparty/mlx/flux/datasets.py
- xinference/thirdparty/mlx/flux/flux.py
- xinference/thirdparty/mlx/flux/layers.py
- xinference/thirdparty/mlx/flux/lora.py
- xinference/thirdparty/mlx/flux/model.py
- xinference/thirdparty/mlx/flux/sampler.py
- xinference/thirdparty/mlx/flux/t5.py
- xinference/thirdparty/mlx/flux/tokenizers.py
- xinference/thirdparty/mlx/flux/trainer.py
- xinference/thirdparty/mlx/flux/utils.py
With MLX, flux.1-dev & flux.1-schnell now can run on Mac with Apple silicon chips.
https://github.com/user-attachments/assets/042adcaa-0fdf-4d0e-afc1-4f5fb492c445
> FEAT: added MLX support for Flux.1

- .github/workflows/docker-cd.yaml
- .github/workflows/python.yaml
- doc/source/conf.py
- doc/source/getting_started/installation_npu.rst
- doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation_npu.po
- doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/image.po
- doc/source/models/builtin/image/got-ocr2_0.rst
- doc/source/models/builtin/image/index.rst
- doc/source/models/model_abilities/image.rst
- pyproject.toml
- setup.cfg
- xinference/constants.py
- xinference/core/tests/test_continuous_batching.py
- xinference/core/worker.py
- xinference/model/audio/core.py
- xinference/model/core.py
- xinference/model/embedding/core.py
- xinference/model/image/core.py
- xinference/model/image/ocr/got_ocr2.py
- xinference/model/llm/__init__.py
- xinference/model/llm/core.py
- xinference/model/llm/llm_family.py
- xinference/model/llm/llm_family_openmind_hub.json
- xinference/model/rerank/core.py
- xinference/model/utils.py
- xinference/model/video/core.py
- xinference/web/ui/src/scenes/launch_model/modelCard.js
add download from openmind_hub
> FEAT: add download from openmind_hub

- .github/workflows/python.yaml
- setup.cfg
- xinference/deploy/docker/requirements.txt
- xinference/deploy/docker/requirements_cpu.txt
- xinference/model/audio/model_spec.json
- xinference/model/audio/tests/test_chattts.py
- The ChatTTS model needs to be updated for ChatTTS 0.2.1
> BUG: Compat with ChatTTS 0.2.1

- xinference/conftest.py
- xinference/deploy/cmdline.py
- xinference/deploy/utils.py
Fix issues introduced by #2443 and #2457
> BUG: transformers logs missing

- xinference/model/image/stable_diffusion/core.py
> BUG: fix variant error for image model

- xinference/deploy/docker/cpu.Dockerfile
Tested: https://github.com/xorbitsai/inference/actions/runs/12082432613/job/33693500860
> BUG: llama-cpp-python 0.3.2 build issue in cpu Docker

- xinference/model/llm/utils.py
> FEAT: Support qwen2.5-coder-instruct model for tool calls

- xinference/model/llm/llm_family.py
Reduce code redundancy by setting default values
> FEAT: Reduce code redundancy by setting default values

- doc/source/models/builtin/image/hunyuandit-v1.2-distilled.rst
- doc/source/models/builtin/image/hunyuandit-v1.2.rst
- doc/source/models/builtin/image/index.rst
- xinference/model/image/model_spec.json
- xinference/model/image/model_spec_modelscope.json
- xinference/model/video/model_spec_modelscope.json
> FEAT: support hunyuan-dit text2image

- xinference/model/llm/utils.py
- xinference/model/llm/vllm/core.py
support cline with vllm engine, i have test with vllm 0.6.1.post2.
1. vllm version
2. gradio diaglog
3. vscode+cline
close #2659
> FEAT: support cline for vllm engine

- xinference/model/llm/transformers/qwen2_vl.py
只对代码做了小改动
支持的环境：
torch_npu-2.10.post8
pip install attr
安装cann否则有算子不支持：
```
wget https://ascend-repo.obs.cn-east-2.myhuaweicloud.com/Milan-ASL/Milan-ASL%20V100R001C17SPC701/Ascend-cann-toolkit_8.0.RC1.alpha001_linux-"$(uname -i)".run
bash Ascend-cann-toolkit_8.0.RC1.alpha001_linux-"$(uname -i)".run --install
wget https://ascend-repo.obs.cn-east-2.myhuaweicloud.com/Milan-ASL/Milan-ASL%20V100R001C17SPC701/Ascend-cann-kernels-910b_8.0.RC1.alpha001_linux.run
bash Ascend-cann-kernels-910b_8.0.RC1.alpha001_linux.run --install
source /usr/local/Ascend/ascend-toolkit/set_env.sh
```
使用torch_npu-2.10.post8的原因是该版本支持了isin
https://gitee.com/ascend/pytorch/issues/I9JGYU
> FEAT: support qwen2vl run on ascend npu

- xinference/web/ui/src/locales/en.json
- xinference/web/ui/src/locales/zh.json
- xinference/web/ui/src/scenes/launch_model/modelCard.js
> ENH: [UI] Update Button Style and Interaction Logic for Editing Cache in Model Card.

- .github/workflows/python.yaml
- setup.cfg
Refer to https://github.com/Blaizzy/mlx-vlm/issues/173
> BUG: pin mlx<0.22.0 to prevent qwen2_vl failing in mlx-vlm

- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/vllm/core.py
https://github.com/vllm-project/vllm/issues/12465
> FEAT: Support qwen-2.5-instruct-1m

- xinference/core/resource.py
- xinference/core/utils.py
- xinference/device_utils.py
Add gpu utilization info when workers report status.
> enh: add gpu utilization info

- setup.cfg
- xinference/deploy/docker/requirements.txt
- xinference/deploy/docker/requirements_cpu.txt
- xinference/model/audio/kokoro.py
- xinference/model/audio/model_spec.json
- xinference/model/audio/tests/test_kokoro.py
> ENH: Update Kokoro model

- doc/source/getting_started/installation.rst
- doc/source/models/builtin/llm/deepseek-r1.rst
- doc/source/models/builtin/llm/deepseek-v3.rst
- doc/source/models/builtin/llm/index.rst
- doc/source/user_guide/backends.rst
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/sglang/core.py
- xinference/model/llm/vllm/core.py
This PR supported deepseek-v3 and deepseek-r1.
The distributed inference based on vllm/sglang/mlx will come soon.
> FEAT: support deepseek-v3 and deepseek-r1

- .github/workflows/python.yaml
transformers 4.49 breaks GOT 2.0 model.
> TST: Pin CI transformers<4.49

- xinference/web/ui/src/components/MenuSide.js
- xinference/web/ui/src/components/copyComponent/copyComponent.js
- xinference/web/ui/src/locales/en.json
- xinference/web/ui/src/locales/zh.json
- xinference/web/ui/src/scenes/launch_model/components/copyComponent.js
- xinference/web/ui/src/scenes/launch_model/components/drawer.js
- xinference/web/ui/src/scenes/launch_model/components/pasteDialog.js
- xinference/web/ui/src/scenes/launch_model/modelCard.js
- xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.css
> FEAT: [UI] support form parameters and command line conversion.

- xinference/web/ui/src/locales/en.json
- xinference/web/ui/src/locales/zh.json
- xinference/web/ui/src/scenes/running_models/index.js
https://github.com/user-attachments/assets/f7db1f73-f8b3-4168-a257-73e9751c92ac
> ENH: [UI] add copy button

- xinference/model/llm/tests/test_llm_model.py
- xinference/model/llm/tests/test_multimodal.py
- xinference/model/llm/vllm/core.py
fix #2916 
fix #2942
fix #2937
fix #2927
> BUG: fix qwen2.5-vl-7b cannot chat bug

- xinference/deploy/docker/Dockerfile
- xinference/deploy/docker/cpu.Dockerfile
forgot to add ffprobe library support in #2946
> BLD: fix ffprobe library not imported

- xinference/core/scheduler.py
- xinference/deploy/docker/requirements.txt
- xinference/model/llm/core.py
- xinference/model/llm/llama_cpp/core.py
- xinference/model/llm/mlx/core.py
- xinference/model/llm/reasoning_parsers/abs_reasoning_parsers.py
- xinference/model/llm/reasoning_parsers/deepseek_r1_reasoning_parser.py
- xinference/model/llm/sglang/core.py
- xinference/model/llm/tests/test_llm_model.py
- xinference/model/llm/transformers/chatglm.py
- xinference/model/llm/transformers/core.py
- xinference/model/llm/utils.py
- xinference/model/llm/vllm/core.py
- xinference/types.py
> Model ID: deepseek-r1-distill-qwen
> Model Size: 15 Billion Parameters
> Model Format: pytorch
> Model Quantization: none
vLLM without reasoning：
vLLM with reasoning：
Transformers without reasoning：
Transformers with reasoning：
SGLang without reasoning：
SGLang with reasoning：
llama.cpp without reasoning：
pass
llama.cpp with reasoning：
pass
MLX without reasoning：
pass
MLX with reasoning：
pass
> Model ID: qwen2.5-instruct
> Model Size: 5 Billion Parameters
> Model Format: pytorch
> Model Quantization: none
Transformers：
vLLM：
SGLang：
llama.cpp:
MLX:
pass
> FEAT: all engine support reasoning_content

- xinference/model/llm/mlx/core.py
- xinference/model/llm/mlx/tests/test_mlx.py
> BUG: fix max_tokens for MLX VL models.

- xinference/web/ui/src/scenes/launch_model/data/data.js
fixes [2998](https://github.com/xorbitsai/inference/issues/2998)
> BUG:fix vLLM parameter "enable_prefix_caching"

- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
I quantified the Fin-R1 model using gptqmodel and AutoFP8, and now I am adding them to the model card
> FEAT: Support gptq(int4, int8) and fp8 for Fin-R1 model

- xinference/model/llm/vllm/core.py
- xinference/web/ui/src/scenes/launch_model/data/data.js
Add model_quantization parameter to replace the quantization parameter in the vLLM engine
> feat: fix the quantization parameter in the vLLM engine cannot work

- xinference/core/supervisor.py
Add function of Validation of n_worker, intercept if it is greater than the available workers. #3163
> ENH: Add validation of n_worker

- xinference/_compat.py
- xinference/api/restful_api.py
> FEAT: support max_completion_tokens

- xinference/model/llm/vllm/distributed_executor.py
Before the processes(subpool) may be terminated for many times, this may cause hang when stopping vllm workers.
In this PR, vllm worker actors are just destroyed instead of killed, and prevent shutdown called repeatedly in `__del__`.
> BUG: fix stop hang for vllm engine

- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
Please refer to: https://huggingface.co/Qwen/QwQ-32B-GGUF/tree/main
> BUG: Fix qwq gguf model path

- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/transformers/intern_vl.py
- xinference/model/llm/vllm/core.py
> FEAT: InternVL3

- xinference/model/audio/model_spec.json
- xinference/model/audio/model_spec_modelscope.json
> FEAT: support paraformer-zh

- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- xinference/model/llm/vllm/core.py
SeaLLMs - Large Language Models for Southeast Asia
> FEAT:support SeaLLMs-v3

- xinference/core/chat_interface.py
> FEAT: add thinking process in gradio chat interface

- xinference/core/chat_interface.py
> ENH: update gradio interface for chat model

- xinference/core/chat_interface.py
Fixes: https://github.com/xorbitsai/inference/issues/3093
> ENH: Set gradio default concurrency to cpu count

- xinference/model/llm/transformers/gemma3.py
> BUG: fix gemma-3-it max_tokens

- xinference/core/supervisor.py
> BUG: fix potential progress error

- xinference/deploy/docker/Dockerfile
support flash-attn at Dockerfile to accelerate transformers inference
> BLD: support flash-attn at Dockerfile

- xinference/core/worker.py
- xinference/model/audio/core.py
- xinference/model/audio/model_spec.json
- xinference/model/audio/model_spec_modelscope.json
- xinference/model/video/diffusers.py
make audio model_spec.json and model_spec_modlescope.json  consistent with others.
> REF: Unify audio model abilities

- xinference/model/llm/utils.py
- xinference/model/llm/vllm/core.py
> BUG: fix the processing logic for inference content parsing and tool calls

- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
add mlx-community/Qwen2.5-VL-32B-Instruct-4bit 
add mlx-community/Qwen2.5-VL-32B-Instruct-8bit 
Fixes #3367
> ENH: add mlx-community/Qwen2.5-VL-32B-Instruct

- xinference/model/llm/transformers/cogvlm2.py
- xinference/model/llm/transformers/glm4v.py
- xinference/model/llm/transformers/minicpmv26.py
- xinference/model/llm/transformers/qwen_vl.py
> BUG: fix Model._get_full_prompt() takes 3 positional arguments but 4 were given

- xinference/web/ui/src/components/MenuSide.js
- xinference/web/ui/src/locales/en.json
- xinference/web/ui/src/locales/zh.json
> ENH: [UI] add a documentation link button in side menu

- xinference/model/llm/llama_cpp/core.py
- xinference/model/llm/llm_family.json
- xinference/model/llm/llm_family_modelscope.json
- Use unsloth gguf
- llama.cpp backend support sub param:
> ENH: QwQ use unsloth gguf

- xinference/model/llm/llm_family_modelscope.json
Please use VLLM V0 mode
export VLLM_USE_V1=0
> FEAT: Qwen3-235B-A22B GPTQ Quantization Int4 Int8

- xinference/web/ui/src/components/MenuSide.js
- xinference/web/ui/src/components/versionLabel.js
> ENH: [UI] display version info in side menu

- xinference/api/restful_api.py
- xinference/core/media_interface.py
- xinference/core/model.py
- xinference/model/video/core.py
- xinference/model/video/diffusers.py
- xinference/model/video/tests/test_diffusers_video.py
- xinference/web/ui/src/scenes/running_models/index.js
This PR introduced video UI.
Text to video:
Image to video:
> FEAT: video UI

- xinference/core/media_interface.py
- xinference/model/image/model_spec.json
- xinference/model/image/model_spec_modelscope.json
> ENH: add modelscope support for kolors

- xinference/model/audio/model_spec.json
- xinference/model/audio/model_spec_modelscope.json
- Paraformer语音识别-中文-通用-16k-离线-large-长音频版(paraformer-zh-long)
iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
- Paraformer分角色语音识别-中文-通用(paraformer-zh-spk)
iic/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn
- Paraformer语音识别-中文-通用-16k-离线-large-pytorch(paraformer-zh)
iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
- Paraformer语音识别-中文-通用-16k-离线-large-热词版(paraformer-zh-hotword)
iic/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404
> FEAT: add some other paraformer series models

- xinference/core/scheduler.py
- xinference/model/llm/transformers/core.py
- xinference/model/llm/transformers/gemma3.py
- xinference/model/llm/transformers/utils.py
Fixes #3118 
Fixes #1945 
Make gemma3 chat model support continuous batching
> ENH: Supports `HybridCache` in `transformers` lib, mainly for `gemma3` chat model

- xinference/deploy/cmdline.py
- The first chunk of stream output may have no content (None).
> BUG: Fix cmdline

- xinference/model/audio/chattts.py
- xinference/model/audio/cosyvoice.py
- xinference/model/audio/tests/test_chattts.py
- xinference/model/audio/tests/test_cosyvoice.py
- xinference/model/audio/utils.py
Fixes: https://github.com/xorbitsai/inference/issues/3573
> ENH: Support pcm response_format

- xinference/core/supervisor.py
- xinference/core/tests/test_restful_api.py
> ENH: add more abilities for builtin model families API

- xinference/deploy/docker/Dockerfile
- xinference/deploy/docker/requirements-ml.txt
> BLD: pin flash-attn & flashinfer-python version and limit sgl-kernel version

- xinference/model/embedding/__init__.py
- xinference/model/embedding/custom.py
- xinference/model/embedding/embed_family.py
Fixes #3668 
About the removed code, it's duplicated and not used.
> BUG: fix custom embedding

- xinference/model/audio/fish_speech.py
- xinference/model/audio/tests/test_fish_speech.py
- xinference/model/audio/utils.py
https://github.com/xorbitsai/inference/issues/3573
> ENH: FishSpeech support pcm

- xinference/deploy/docker/Dockerfile
fix the wrong version & install wget
> BLD: Update Dockerfile

- .github/workflows/python.yaml
- README_zh_CN.md
- setup.cfg
- xinference/model/llm/core.py
- xinference/model/llm/mlx/core.py
- xinference/model/llm/reasoning_parser.py
- xinference/model/llm/sglang/core.py
- xinference/model/llm/transformers/chatglm.py
- xinference/model/llm/transformers/core.py
- xinference/model/llm/transformers/multimodal/cogagent.py
- xinference/model/llm/utils.py
- xinference/model/llm/vllm/core.py
> BUG: fix `<think>` wrongly added when set `chat_template_kwargs {"enable_thinking": False}`

- doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_docker_image.po
- xinference/deploy/docker/requirements-ml.txt
- xinference/deploy/docker/requirements_cpu-ml.txt
Fixes #3733
Fixes #3731
Fixes #3729
> BLD: pin transformers version at 4.52.4 to fix "Failed to import module 'SentenceTransformer'" error

- xinference/model/llm/vllm/core.py
> BUG: add message preprocessing to ensure that content is not null

- xinference/model/audio/model_spec.json
- xinference/model/llm/vllm/core.py
Fixes https://github.com/xorbitsai/inference/issues/3569
> ENH: add modelscope for fish speech 1.5

- .github/workflows/python.yaml
- xinference/model/llm/tests/test_llm_model.py
- xinference/model/llm/utils.py
> BUG: resolve issue where AI output was lost when no tool was selected for function call #3767

- xinference/model/llm/reasoning_parser.py
- xinference/model/llm/sglang/core.py
- xinference/model/llm/tests/test_llm_model.py
- xinference/model/llm/utils.py
- xinference/model/llm/vllm/core.py
> BUG: fix error in `content` output at `reasoning_content`, when using `enable_thinking` in `chat_template_kwargs`

- xinference/model/llm/llm_family.json
This is a mistake — a repository that should not exist in the first place.
> FIX: GLM4.1V Repository URL

- xinference/model/rerank/core.py
bug fix:修复qwen3 reranker系列 GPU显存异常占用问题
> BUG: Fix abnormal GPU memory usage in Qwen3 Reranker

- doc/source/models/builtin/llm/deepseek-v3-0324.rst
- xinference/model/llm/llm_family.json
Added mlx support for deepseek-v3-0324, which is readily available on Hugginface.
> ENH: Added mlx support for deepseek-v3-0324

- xinference/model/llm/llm_family.json
- xinference/model/llm/utils.py
> ENH: Add qwen3 new model to tool call list

- xinference/api/restful_api.py
- xinference/core/model.py
- xinference/model/llm/sglang/core.py
sglang support streaming function call
> feat: sglang support streaming function call

- xinference/core/supervisor.py
- xinference/model/core.py
- xinference/model/embedding/vllm/core.py
- xinference/model/llm/tests/test_harmony.py
- xinference/model/llm/transformers/multimodal/core.py
- xinference/model/llm/transformers/utils.py
- xinference/model/rerank/__init__.py
- xinference/model/rerank/cache_manager.py
- xinference/model/rerank/core.py
- xinference/model/rerank/custom.py
- xinference/model/rerank/model_spec.json
- xinference/model/rerank/rerank_family.py
- xinference/model/rerank/sentence_transformers/__init__.py
- xinference/model/rerank/sentence_transformers/core.py
- xinference/model/rerank/sentence_transformers/tests/test_sentence_transformers.py
- xinference/model/rerank/tests/test_rerank.py
- xinference/model/rerank/vllm/__init__.py
- xinference/model/rerank/vllm/core.py
- xinference/model/rerank/vllm/tests/test_vllm.py
- xinference/model/utils.py
- xinference/ui/web/ui/src/scenes/launch_model/modelCard.js
- xinference/ui/web/ui/src/scenes/register_model/components/addModelSpecs.js
- xinference/ui/web/ui/src/scenes/register_model/index.js
- xinference/ui/web/ui/src/scenes/register_model/registerModel.js
添加了对rerank引擎切换，以及推理vllm的支持，模仿 embedding 部分做的
> FEAT: Add support for switching rerank model engines and support for rerank of vllm engine

- xinference/model/rerank/core.py
- xinference/model/rerank/sentence_transformers/core.py
> BUG: fix rerank model creation

- doc/source/models/builtin/video/index.rst
- doc/source/models/builtin/video/wan2.2-a14b.rst
- doc/source/models/builtin/video/wan2.2-i2v-a14b.rst
- doc/source/models/builtin/video/wan2.2-ti2v-5b.rst
- xinference/model/video/model_spec.json
Generated video:
https://github.com/user-attachments/assets/503303d6-d878-4037-b9e2-c9e8c0c5ed94
> FEAT: Wan 2.2

- xinference/model/image/model_spec.json
更新GOT-OCR环境依赖，以处理历史遗留[问题](https://github.com/xorbitsai/inference/issues/4018)
> ENH: Update the environment dependencies for GOT-OCR2

- xinference/model/audio/kokoro.py
> BUG: Fix Kokoro-82M can't run on GPU

- xinference/model/embedding/vllm/core.py
> BUG: [embeddings] fix parsing str type hf_overrides for vllm engine

- xinference/core/supervisor.py
check model name is duplicate before worker register model
> BUG: fix register_model when model name is duplicated

- xinference/api/restful_api.py
- xinference/client/restful/async_restful_client.py
- xinference/client/restful/restful_client.py
- xinference/model/embedding/sentence_transformers/tests/test_sentence_transformers.py
- xinference/model/image/model_spec.json
- xinference/model/image/stable_diffusion/core.py
- xinference/ui/gradio/media_interface.py
- xinference/ui/web/ui/src/scenes/launch_model/data/data.js
> FEAT: [model] qwen-image-edit-2509

- xinference/model/llm/__init__.py
- xinference/model/llm/utils.py
- xinference/ui/web/ui/src/locales/en.json
- xinference/ui/web/ui/src/locales/ja.json
- xinference/ui/web/ui/src/locales/ko.json
- xinference/ui/web/ui/src/locales/zh.json
- xinference/ui/web/ui/src/scenes/register_model/components/addVirtualenv.js
- xinference/ui/web/ui/src/scenes/register_model/registerModel.js
> BUG: Fix the issue where registered models cannot use tools

- xinference/model/llm/llm_family.json
- xinference/model/llm/vllm/core.py
> FEAT: [model] baichuan-M2
