xinference/model/llm/core.py
Resolve #49 
- increase context length to 2k
- determine gpu layers based on model size
- handle import error for llama_cpp
=> ENH: edit Llama parameters

xinference/client.py
RuntimeError: Failed to launch model, detail: [address=[0.0.0.0:53237](http://0.0.0.0:53237/), pid=1870] 'str' object cannot be interpreted as an integer
=> BUG: RuntimeError when launching model using kwargs whose value is of type int

.github/workflows/python.yaml, setup.cfg, xinference/core/service.py
`baichuan-base` and `baichuan-chat` depend on `cpm_kernels` module, but `cpm_kernels` cannot run on Darwin system.
=> BUG: baichuan-chat and baichuan-base don't support MacOS

xinference/core/tests/test_restful_api.py, xinference/model/llm/core.py, xinference/tests/test_client.py
As of the current CLI version for launching model, there is no direct option to specify embeddings, and the default value for embeddings is False.
However, attempting to use the model for embedding without explicitly setting `embedding=True` will result in the error `Llama model must be created with embedding=True to call this method`.
=> BUG: Set default embedding to be True

README_ja_JP.md
Update Japanese README.
refs https://github.com/xorbitsai/inference/pull/228
=> DOC: Update README_ja_JP.md

xinference/core/restful_api.py
fix #306.
Chatgml ggml's chat method does not have the optional argument `system_prompt`, which is different from other LLMs.
=> BUG: handle ChatGLM ggml specific case for RESTful API

xinference/deploy/cmdline.py, xinference/deploy/worker.py
Now if user specified log-level in their command line, like: xinference --log-level debug(any upper lower case of debug), all the processes, including main and subprocess, will have correct log level corresponding to the log log level input.
=> BUG: Fix log level on subprocess

xinference/model/llm/ggml/chatglm.py
resolves #163 
Although the parameters are successfully passed to the model, ChatGLM often generates nothing if the max_length is set to small values (~40 tokens) when I was testing it locally. It seems the model is simply not trained on short-sentence snippets and therefore is incapable of chatting in them.
=> BUG: Chatglm max_length doesn't work

xinference/model/llm/llm_family.json
Resolve #327 
I did not remove the prompt entirely, but maintained a generic `You are a helpful AI assistant` as a placeholder so the chat history format is the exact same.
That being said, I did run some tests with the same settings to make sure the new system prompt is working.
Left image uses the new system prompt while the right image uses the old.
<p align="center">
&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;
</p>
=> ENH: Update System Prompt for llama-2-chat

doc/source/models/builtin/index.rst, doc/source/models/builtin/vicuna-v1.5-16k.rst, doc/source/models/builtin/vicuna-v1.5.rst, xinference/model/llm/llm_family.json
Support 7B and 13B models for each model format
Resolves #296
=> FEAT: Support Vicuna-v1.5 and Vicuna-v1.5-16k

doc/source/models/builtin/index.rst, doc/source/models/builtin/wizardmath-v1.0.rst, xinference/model/llm/llm_family.json, xinference/model/llm/tests/test_utils.py, xinference/model/llm/utils.py
=> FEAT: wizardmath

xinference/client.py
Currently, although i can pass the stream parameter and stream the response, it's actually still blocking and waits for the complete result before streaming the output. To achieve non-blocking streaming, i need to combine it with the stream parameter of requests.
=> FEAT: Adding support for stream returning completion results

.github/workflows/python.yaml, setup.cfg
As of version 0.1.79, the llama-cpp-python no longer supports ggmlv3. Therefore, it is necessary to lock its version until we transition the built-in ggmlv3 models to gguf.
=> CHORE: lock llama-cpp-python version

xinference/model/llm/llm_family.py
=> EHN: auto retry download on network errors

xinference/deploy/cmdline.py
=> ENH: help message for CLI

.github/workflows/python.yaml, setup.cfg, xinference/client.py, xinference/core/model.py, xinference/core/restful_api.py, xinference/tests/test_client.py
Fix: https://github.com/xorbitsai/inference/issues/448
=> ENH: Safe iterate stream of ggml model

setup.cfg, xinference/model/llm/ggml/ctransformers.py, xinference/model/llm/llm_family.json
Resolve #508
Adding Mistral-7B-v0.1 and Mistral-Instruct-7B-v0.1, with both GGML and PyTorch support.
GGUFv2 models has been tested locally on my computer and works properly. However, PyTorch models are a bit too big to run on my computer. I've documented the PyTorch model specifics in their families, but I'd appreciate a hand pulling this and checking if everything's functioning. Thanks!
=> FEAT: Support Mistral & Mistral-Instruct

xinference/core/supervisor.py, xinference/deploy/cmdline.py, xinference/model/core.py
Users now can use `xinference registrations --model-type=embedding` to list available embedding models.
Resolves #511
=> BUG: Fix listing embedding models

README.md, README_zh_CN.md, xinference/core/restful_api.py, xinference/model/llm/ggml/llamacpp.py, xinference/model/llm/ggml/tests/test_gguf.py, xinference/types.py
Example for passing grammar:
```Python
grammar = r"""
root ::= answer
answer ::= ("Apple" | "Banana" | "Orange")
"""
completion = model.chat(
"Tell me a random fruit name.",
generate_config={"max_tokens": 10, "grammar": grammar},
)
```
=> FEAT: Support grammar-based sampling for ggml models

setup.cfg
To address recent incompatible changes in `transformers`, like #505.
=> ENH: lock transformers version

xinference/model/llm/pytorch/falcon.py
Try to fix the error ` got multiple values for keyword argument 'trust_remote_code'` when load falcon-instruct model, the related the issue https://github.com/xorbitsai/inference/issues/498
=> BUG: set trust_remote_code to true by default

xinference/model/llm/ggml/llamacpp.py
Bug description:
In the function `_convert_ggml_to_gguf`, when one model was converted and the `__valid` file was created to mark this job was done. However, when another quantization model tries to convert from ggml to gguf, it could be skipped due to the `__valid` file exists, and this error `Model path does not exist: /path/.xinference/cache/llama-2-chat-ggufv2-13b/llama-2-chat.q4_0.ggufv2` could come up
Solution:
Add quantization to valid file name of valid file
=> BUG: add quantization to valid file name

xinference/model/llm/llm_family_modelscope.json
Currently only supports pytorch format
Fixes #552
=> ENH: Support downloading code-llama family models from ModelScope

xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json
In document, it says:  ability of model baichuan-2-chat is ['embed', 'chat'], but in llm_family.json that is "model_ability": [      "embed",  "generate",  "chat"   ]
=> BUG: remove "generate" ability from Baichuan-2-chat json config

.github/workflows/release.yaml
https://github.com/aresnow1/inference/actions/runs/6688050241/job/18169539702
=> CHORE: Use python3.10 to build and release

setup.cfg, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json
Models such as Zephyr require version v0.34.0 or higher of transformers. However, existing models, particularly Chinese models, would fail due to an incompatible change introduced in v4.34.0. Therefore, we locked the version to v4.33.1.
Recently, the model providers have addressed this issue. As a result, I have updated the model's revision and removed the version lock.
=> BUG: fix transformers compatibility

doc/source/examples/index.rst
1. Llama index: Use the latest doc's permalink: https://docs.llamaindex.ai/en/stable/examples/llm/xinference_local_deployment.html
2. Link to Zhihu post instead of  X
3. Link a post to Dify's tutorial for deploying baichuan
=> DOC: Change links for some tutorials

xinference/api/restful_api.py, xinference/client/oscar/actor_client.py, xinference/client/restful/restful_client.py, xinference/core/model.py, xinference/core/supervisor.py, xinference/core/tests/test_restful_api.py, xinference/core/worker.py
Add a new parameter `request_limits` to `launch_model` interface to control the visit count on a single model instance at the same time.
=> ENH: Supports request limits for the model

xinference/core/model.py, xinference/core/tests/test_worker.py, xinference/core/worker.py
When there are only one GPU available and user launches vLLM-backend models first, then launches embedding models to GPU, `No slot available` error would be raised.
Here' the changes:
- Embedding models use their own slots, no relation with LLM models.
- The embedding model will first avoid the card where the LLM model is located, and if there is no slot, the user will be prompted to launch the embedding model first.
- After finding the cards where the embedding models can be placed, try to equalize the load (number of models) between the cards.
=> BUG: `No slot available` error for embedding and LLM model on one card

xinference/client/tests/test_client.py, xinference/core/tests/test_worker.py, xinference/core/worker.py, xinference/model/core.py, xinference/model/embedding/core.py, xinference/model/image/core.py, xinference/model/llm/core.py, xinference/model/llm/llm_family.py, xinference/web/ui/src/scenes/running_models/index.js
The `list models` and `desc model` APIs have been updated to include the model address and the accelerators in use. Corresponding updates have been made to the frontend. The columns and actions now vary depending on the model type.
=> ENH: running model location & accelerators

.github/workflows/python.yaml, doc/source/models/builtin/bge-reranker-base.rst, doc/source/models/builtin/bge-reranker-large, doc/source/models/builtin/index.rst, doc/source/user_guide/client_api.rst, xinference/api/restful_api.py, xinference/client/oscar/actor_client.py, xinference/client/restful/restful_client.py, xinference/core/model.py, xinference/core/supervisor.py, xinference/model/core.py, xinference/model/embedding/core.py, xinference/model/image/core.py, xinference/model/rerank/__init__.py, xinference/model/rerank/core.py, xinference/model/rerank/model_spec.json, xinference/model/rerank/model_spec_modelscope.json, xinference/model/rerank/tests/__init__.py, xinference/model/rerank/tests/test_rerank.py, xinference/types.py
example for launching rerank model:
```Python
model_uid = client.launch_model(
model_name="bge-reranker-large", model_type="rerank"
)
model = client.get_model(model_uid)
query = "A man is eating pasta."
corpus = [
"A man is eating food.",
"A man is eating a piece of bread.",
"The girl is carrying a baby.",
"A man is riding a horse.",
"A woman is playing violin.",
"Two men pushed carts through the woods.",
"A man is riding a white horse on an enclosed ground.",
"A monkey is playing drums.",
"A cheetah is running behind its prey.",
]
print(model.rerank(corpus, query))
```
=> FEAT: Support rerank models

.github/workflows/python.yaml, examples/FunctionCall.ipynb, setup.cfg, xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/conftest.py, xinference/core/tests/test_restful_api.py, xinference/core/tests/test_types.py, xinference/model/llm/ggml/chatglm.py, xinference/model/llm/llm_family.json, xinference/model/llm/pytorch/chatglm.py, xinference/model/llm/tests/test_utils.py, xinference/model/llm/utils.py, xinference/types.py
Support tool calls for ChatGLM3, but the response function arguments are different:
Post URL: `http://localhost:42183/v1/chat/completions`
payload json:
```json
{
"model": "test_tool",
"messages": [
{
"role": "user",
"content": "帮我查询股票10111的价格"
}
],
"tools": [
{
"type": "function",
"function": {
"name": "track",
"description": "追踪指定股票的实时价格",
"parameters": {
"type": "object",
"properties": {
"symbol": {
"description": "需要追踪的股票代码"
}
},
"required": [
"symbol"
]
}
}
},
{
"type": "function",
"function": {
"name": "text-to-speech",
"description": "将文本转换为语音",
"parameters": {
"type": "object",
"properties": {
"text": {
"description": "需要转换成语音的文本"
},
"voice": {
"description": "要使用的语音类型（男声、女声等）"
},
"speed": {
"description": "语音的速度（快、中等、慢等）"
}
},
"required": [
"text"
]
}
}
}
],
"stop": [
"\n"
]
} …
```
=> FEAT: ChatGLM3  tool calls

xinference/client/tests/test_client.py, xinference/model/embedding/core.py, xinference/model/utils.py
Fixes: https://github.com/xorbitsai/inference/issues/707
=> BUG: Auto patch trust remote code for embedding model

xinference/web/ui/public/index.html
fix https://github.com/xorbitsai/inference/issues/639
=> ENH: upgrade insecure requests when necessary

xinference/web/ui/src/components/apiContext.js, xinference/web/ui/src/components/errorMessageSnackBar.js, xinference/web/ui/src/scenes/launch_model/embeddingCard.js, xinference/web/ui/src/scenes/launch_model/index.js, xinference/web/ui/src/scenes/launch_model/modelCard.js, xinference/web/ui/src/scenes/register_model/index.js
Previsouly, when some error happens, we have to open the `F12`  tool page to find the error, which is not easy.
Now, some key errors would just be shown on Web UI via Snackbar.
For example:
Additionally, fix a issue that web will keep sending requests to backend to get builtin promot styles.
=> ENH: [UI] Error can be shown on web UI directly via Snackbar

xinference/web/ui/src/scenes/launch_model/embeddingCard.js, xinference/web/ui/src/scenes/launch_model/index.js, xinference/web/ui/src/scenes/launch_model/launchCustom.js, xinference/web/ui/src/scenes/launch_model/launchLLM.js, xinference/web/ui/src/scenes/launch_model/modelCard.js
=> ENH: [UI] Support unregistering custom model on web UI

xinference/api/restful_api.py, xinference/client/tests/test_client.py, xinference/core/tests/test_restful_api.py, xinference/model/llm/ggml/llamacpp.py, xinference/model/llm/llm_family.json, xinference/model/llm/pytorch/chatglm.py, xinference/model/llm/pytorch/core.py, xinference/model/llm/utils.py, xinference/types.py
Close: https://github.com/xorbitsai/inference/issues/732
=> FEAT: Support gorilla openfunctions v1

xinference/web/ui/src/scenes/launch_model/modelCard.js
Fix #765 
The bug is caused by how the `cache_status` property was accessed in our code. This fix should help us avoid the unexpected crashes. Here is a quick break down of the change.
**The Issue:**
We were directly accessing `cache_status` on the `specs[0]` object. If `specs[0]` or `cache_status` does not exist (in this case the card is filtered out by the search), the code would throw an error.
**The Fix:**
I've introduced optional chaining (`?.`) and the nullish coalescing operator (`??`)to address the nonexistent property issue:
Before:
```javascript
const cached = modelFormat === 'pytorch'
? specs[0].cache_status &&
specs[0].cache_status === true
: specs[0].cache_status &&
specs[0].cache_status[index] === true
```
After:
```javascript
const cached = modelFormat === 'pytorch'
? …
```
=> BUG: UI Crash on Search when `model_format` and `model_size` have been selected

README.md, README_ja_JP.md, README_zh_CN.md, doc/source/models/builtin/llm/index.rst, doc/source/models/builtin/llm/openhermes-2.5.rst, xinference/model/llm/llm_family.json
Fix #775 
I have tested the GGUF model locally with Llama.cpp but did not test the PyTorch ones due to the lack of CUDA support.
I played around with OpenHermes 2.5 on my laptop and generally believe it to be the best 7B local model we have so far. Here are some outputs from the **Q2_K quantization** (I'm sure other quantizations will perform even better) with 0 temperature for deterministic output, if anyone is interested:
<details> 
<summary>screenshots</summary> 
</details>
=> FEAT: Support OpenHermes 2.5

xinference/constants.py
=> BUG: When changing `XINFERENCE_HOME` env, the model files are still stored  where they were.

xinference/core/supervisor.py, xinference/core/worker.py
=> BUG: when terminating worker by `ctrl+C`, supervisor does not remove worker information

xinference/types.py
Fix #783 
Seems like the `CreateCompletionCTransformers` function is not taking in "streaming" as a keyword when creating the config. I added it and that fixes the error encountered when streaming GPT-2.
Now we should be able to stream response with the CTransformers library.
=> ENH: Enable streaming on Ctransformer

xinference/deploy/cmdline.py
When `model_size_in_billions` is not provided, the operation involving this field should be ignored.
Fixes #807
=> BUG: launch method exception (#807)

.github/workflows/python.yaml, xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/model/image/model_spec.json, xinference/model/image/stable_diffusion/core.py, xinference/model/image/tests/test_stable_diffusion.py
- `text_to_image` support kwargs
=> FEAT: Support sd-turbo

README.md, README_zh_CN.md, doc/source/models/builtin/llm/index.rst, doc/source/models/builtin/llm/phi-2.rst, doc/source/models/builtin/llm/skywork-math.rst, doc/source/models/builtin/llm/skywork.rst, setup.cfg, xinference/model/llm/llm_family.json
Fix #806
Added support for Phi-2 in GGUF and PyTorch. GGUF works as expected when tested locally. Would appreciate it if someone can test PyTorch locally as well.
Phi-2 supports a variety of input formats, so I thought the generate UI would be more appropriate. 
<details> 
<summary>Input formats from Hugging Face page](https://huggingface.co/microsoft/phi-2) </summary> 
> QA Format:
> You can provide the prompt as a standalone question as follows:
> ```
> Write a detailed analogy between mathematics and a lighthouse.
> ```
> where the model generates the text after "." . To encourage the model to write more concise answers, you can also try the following QA format using "Instruct: <prompt>\nOutput:"
> ```
> Instruct: Write a detailed analogy between mathematics and a lighthouse.
> Output: …
```
=> FEAT: Support Phi-2

xinference/core/model.py, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json
- Add gptq quanization for qwen 1.8b.
- Known issue: https://modelscope.cn/models/qwen/Qwen-1_8B-Chat-Int4 has bugs, it can't works with vLLM.
```python
2024-01-08 08:03:57,300 xinference.core.worker 129598 ERROR    Failed to load model qwen-chat-1-0
Traceback (most recent call last):
File "/home/codingl2k1/inference/xinference/core/worker.py", line 381, in launch_builtin_model
await model_ref.load()
File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/context.py", line 227, in send
return self._process_result_message(result)
File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
raise message.as_instanceof_cause()
File …
```
=> FEAT: qwen 1.8b gptq

xinference/model/image/stable_diffusion/core.py
the `size` param use '*' as seperator only. it should be better to support other characters such as 'x' or any other non-integers.
=> ENH: make the size param of *_to_image more compatible

xinference/deploy/docker/Dockerfile
xinference在k8s环境中以pod的形式启动，出现报错：
`ImportError: libcuda.so.1: cannot open shared object file: No such file or directory`
需要找到libcuda.so.1的路径
`sudo find /usr/ -name 'libcuda.so.*'`
添加环境路径环境变量，如我的路径是:/usr/local/cuda-12.1/compat, 添加环境变量
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.1/compat`
=> BUG: fix libcuda.so.1: cannot open shared object file

xinference/api/restful_api.py, xinference/core/event.py, xinference/core/supervisor.py, xinference/core/tests/test_restful_api.py, xinference/core/worker.py
- Add a router to the restful api: `/v1/models/{model_uid}/events`
- Example of the query result:
```python
[
{
"event_type": "INFO",
"event_ts": 1705905654,
"event_content": "Launch model"
},
{
"event_type": "ERROR",
"event_ts": 1705905669,
"event_content": "Remote server 127.0.0.1:49371 closed"
},
{
"event_type": "INFO",
"event_ts": 1705905670,
"event_content": "Terminate model"
}
]
```
=> FEAT: Support events

xinference/model/audio/model_spec.json, xinference/model/rerank/core.py
- 增加了 whisper.small 和 belle distil whisper zh 系列模型，其中后者不支持 translations
- 修复了rerank模型启动时不能正常给cross encoder传参的问题
=> FEAT: add whisper.small and belle distilwhisper model, fix parameter in rerank

setup.cfg, xinference/__init__.py, xinference/api/restful_api.py, xinference/core/model.py, xinference/core/supervisor.py, xinference/core/worker.py, xinference/deploy/worker.py, xinference/device_utils.py, xinference/model/audio/whisper.py, xinference/model/image/stable_diffusion/core.py, xinference/model/llm/pytorch/compression.py, xinference/model/llm/pytorch/core.py, xinference/model/llm/pytorch/qwen_vl.py, xinference/model/llm/pytorch/spec_decoding_utils.py, xinference/model/llm/pytorch/spec_model.py, xinference/model/llm/pytorch/utils.py, xinference/model/llm/pytorch/yi_vl.py, xinference/model/utils.py, xinference/thirdparty/llava/mm_utils.py
Refactors most device related code into `device_utils` (only `pytorch` backend, `vllm` and `ctransformers` are unsupported, `8bit` and `4bit` are also unsupported), and adds initial Intel GPU support.
You will need `intel-extension-for-pytorch` to run it: https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/installation.html
Tested on Llama2-chat and ChatGlm3.
(for `device_map`, requires https://github.com/huggingface/accelerate/pull/2383)
=> FEAT: Refactor device related code and add initial Intel GPU support

doc/source/models/builtin/llm/gemma-it.rst, doc/source/models/builtin/llm/index.rst, doc/source/models/builtin/llm/llama-2-chat.rst, doc/source/models/builtin/llm/qwen1.5-chat.rst, xinference/deploy/docker/Dockerfile, xinference/model/llm/llm_family.json, xinference/model/llm/utils.py
=> FEAT: Support gemma series model

xinference/api/restful_api.py, xinference/types.py
The `CreateCompletionLlamaCpp` model inherits from the signature of  [`llama_cpp.llama.create_completion`](https://github.com/abetlen/llama-cpp-python/blob/8c71725d5345b2ba325e6d28209875057c5873e6/llama_cpp/llama.py#L1384) which sets `max_tokens` to `16` by default. This invalidates the default value set in [`restful_api.py`](https://github.com/xorbitsai/inference/blob/d53c80a6a82ded81231d22984ff4d02eb3935ae5/xinference/api/restful_api.py#L848) which expects `max_tokens` to be `None` if not set in the request.
=> BUG: Fix early truncation due to `max_token` being default to `16` instead of `1024`

xinference/model/llm/llm_family.json, xinference/model/llm/llm_family.py, xinference/model/llm/llm_family_modelscope.json, xinference/model/llm/tests/test_llm_family.py
This PR adds support for downloading and merging multiple parts of gguf files, like the `q4_k_m` quantization in https://huggingface.co/Qwen/Qwen1.5-72B-Chat-GGUF. It will download `qwen1_5-72b-chat-q4_k_m.gguf.a` and `qwen1_5-72b-chat-q4_k_m.gguf.b`, then merge them into `qwen1_5-72b-chat-q4_k_m.gguf`.
Supports both huggingface and modelscope models.
=> FEAT: Support download and merge multiple parts of gguf files

xinference/web/ui/src/scenes/launch_model/modelCard.js
This PR adds an "N GPU Layers" input to model card if you selected `ggufv2` format, to adjust the number of layers offloaded to GPU when using llama.cpp loader. It will replace the "N-GPU" dropdown (only on `ggufv2` selection).
Special values: `-1`means auto (the old `SIZE_TO_GPU_LAYERS` method), `0` means CPU only.
btw: I'm not sure if I should replace the N-GPU dropdown (Looks like the "N-GPU" selection won't have any effect for llama.cpp), or add a new row to the model card. Maybe we could use a wizard-like page for more configurable options in the future?
=> ENH: Add a dropdown to the web UI to support adjusting GPU offload layers for llama.cpp loader

xinference/api/restful_api.py, xinference/client/common.py, xinference/client/tests/test_client.py
The official API from OpenAI always send a "[DONE]" before it terminates the stream. Although redundant, some clients like [ChatGPT.好友](https://help.chats.li/) rely on it instead of a non-empty `finish_reason` to determine the the end of the stream. So, it might be beneficial to abide by this convension. 
fixes #998
=> ENH: Add "[DONE]" to the end of stream generation for better openai SDK compatibility

setup.cfg, xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/core/supervisor.py, xinference/core/worker.py, xinference/deploy/cmdline.py, xinference/deploy/docker/cpu.Dockerfile, xinference/model/core.py, xinference/model/image/core.py, xinference/model/image/stable_diffusion/core.py, xinference/model/llm/__init__.py, xinference/model/llm/core.py, xinference/model/llm/llm_family.py, xinference/model/llm/pytorch/baichuan.py, xinference/model/llm/pytorch/chatglm.py, xinference/model/llm/pytorch/core.py, xinference/model/llm/pytorch/falcon.py, xinference/model/llm/pytorch/internlm2.py, xinference/model/llm/pytorch/llama_2.py, xinference/model/llm/pytorch/qwen_vl.py, xinference/model/llm/pytorch/vicuna.py, xinference/model/llm/pytorch/yi_vl.py
Related #389 
Fixes #271 
Fixes #840 
Fixes #1041 
1. Download lora from repo: https://huggingface.co/shiroppo/sd_xl_turbo_lora
2. Use `sdxl-turbo`
```
from xinference.client import Client
client = Client("http://127.0.0.1:12306")
model_uid = client.launch_model(model_name="sdxl-turbo", model_type="image", peft_model_path='/home/lichengjie/lora/sd_xl_turbo_lora', image_lora_load_kwargs={"weight_name": "sd_xl_turbo_lora_v1-64dim.safetensors"})
model = client.get_model('sdxl-turbo')
model.text_to_image("papercut, a dragon", size="256*256")
```
1. Download lora from repo: https://huggingface.co/Jungwonchang/Ko-QWEN-7B-Chat-LoRA
2. Use `qwen-chat` 7B:
```
from xinference.client import Client
client = Client("http://127.0.0.1:12306")
model_uid = client.launch_model(model_name="qwen-chat", …
```
=> FEAT: Supports LoRA for LLM and image models

xinference/deploy/cmdline.py
Update cmd help information to keep all help information consistent.
Registers -> Register
Lists -> List
=> ENH: update cmd help info

xinference/core/tests/test_restful_api.py
When llama-cpp-python upgrading to `v0.2.56`, LLM model creating embeddings leads to issues.
We do not support this usage any more. Therefore, remove these tests.
=> TST: Remove testing LLM model creating embedding

xinference/web/ui/src/scenes/launch_model/launchEmbedding.js, xinference/web/ui/src/scenes/launch_model/launchImage.js, xinference/web/ui/src/scenes/launch_model/launchRerank.js
Fixes #1110 
修复后效果如图：
切换模型tab 只会发起一次请求，同时，模型列表可以正常加载
=> BUG: Fixing the issue of model list loading failure caused by a large number of invalid requests on the model list page.

xinference/model/llm/ggml/llamacpp.py
For example, I tried `q3_k_m` quantization of `qwen1.5-chat` on Apple M1 MAX:
=> ENH: Remove quantization limits for Apple METAL device when running model via `llama-cpp-python`

xinference/model/image/__init__.py, xinference/model/image/core.py, xinference/web/ui/src/scenes/launch_model/embeddingCard.js, xinference/web/ui/src/scenes/launch_model/imageCard.js, xinference/web/ui/src/scenes/launch_model/rerankCard.js
=> BUG: Fix cache status for embedding, rerank and image models on the web UI

xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/core/tests/test_restful_api.py, xinference/web/ui/src/scenes/running_models/index.js
This PR add some fields according to https://platform.openai.com/docs/api-reference/models/list while retaining its original fields. Now I'm able to use xinference with https://github.com/open-webui/open-webui
=> ENH: Make GET /v1/models compatible with OpenAI API.

setup.cfg, xinference/client/tests/test_client.py, xinference/conftest.py, xinference/core/tests/test_metrics.py, xinference/deploy/docker/cpu.Dockerfile, xinference/deploy/local.py, xinference/deploy/supervisor.py, xinference/model/llm/pytorch/tests/test_opt.py, xinference/model/llm/vllm/core.py
=> ENH: support vllm>=0.3.1

benchmark/benchmark_latency.py, benchmark/benchmark_serving.py, benchmark/utils.py
`best_of` is supported in OpenAI legacy API [Create Completion](https://platform.openai.com/docs/api-reference/completions/create) and not in [Create Chat Completion](https://platform.openai.com/docs/api-reference/chat/create). So remove it from benchmark.
=> BUG: remove `best_of` from benchmark

doc/source/user_guide/backends.rst, xinference/model/llm/vllm/core.py
add vLLM latest models ``gemma-it``, ``orion-chat``, ``orion-chat-rag``.
FIX https://github.com/xorbitsai/inference/issues/1154
=> ENH: vLLM latest models support

setup.cfg
Support autoawq.
Otherwise, when inferring the AWQ quantization model, it will error that dependencies are missing.
=> BLD: add autoawq in setup

xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/core/supervisor.py, xinference/core/tests/test_worker.py, xinference/core/worker.py, xinference/deploy/cmdline.py
- add `--worker-ip` and `--gpu-idx` in launch command line
- Change the GPU allocation algorithm to maintain the original policy when gpu_idx is not specified, and when gpu_idx is specified, it can be launched as long as the existing model on the GPU is not a vllm model, and there will be a corresponding log.
=> FEAT: force to specify worker ip and gpu idx when launching models

xinference/api/restful_api.py
=> BUG: Increase validator types for thie 'input' parameter of embeddings to match OpenAI API

xinference/thirdparty/omnilmm/chat.py
ValueError: [address=[0.0.0.0:41917](http://0.0.0.0:41917/), pid=2321173] Unrecognized configuration class <class 'xinference.thirdparty.omnilmm.model.omnilmm.OmniLMMConfig'> for this kind of AutoModel: AutoModel.
=> BUG: Fix the launch bug of OmnilMM 12B.

xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json
Both HF and modelscope config files have been added.
=> FEAT: add support for qwen1.5 32B chat model

doc/source/gen_docs.py, doc/source/getting_started/installation.rst, doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po, doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po, doc/source/user_guide/backends.rst, xinference/model/llm/vllm/core.py
=> DOC: auto gen vllm doc & add chatglm3-{32k, 128k} support for vllm

xinference/model/llm/pytorch/qwen_vl.py, xinference/model/llm/pytorch/yi_vl.py
qwen-vl and yi-vl are tested on multiple cards.
deepseek-vl and omniLMM used third party implementation, the multi gpus support is non-trivial, will support at a right point in the future.
=> ENH: support multi gpus for qwen-vl and yi-vl

xinference/model/llm/llm_family.py, xinference/model/llm/pytorch/core.py, xinference/model/llm/tests/test_llm_family.py
Fixes #1194 .
The reason is that the registered vision model can be matched by default pytorch model.
=> BUG: fix custom vision model

xinference/model/llm/llm_family.json
=> FEAT: Support SeaLLM-7B and c4ai-command-r-v01

xinference/model/embedding/model_spec.json, xinference/model/embedding/model_spec_modelscope.json
Fixes #703 .
Model tested already.
=> FEAT: support m3e embedding models

xinference/web/ui/src/components/hotkeyFocusTextField.js, xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js, xinference/web/ui/src/scenes/launch_model/launchCustom.js, xinference/web/ui/src/scenes/launch_model/launchLLM.js
=> FEAT: hotkey to active search

doc/source/getting_started/installation.rst, doc/source/models/builtin/llm/index.rst, doc/source/models/builtin/llm/llama-3-instruct.rst, doc/source/models/builtin/llm/llama-3.rst, doc/source/user_guide/backends.rst, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json, xinference/model/llm/tests/test_utils.py, xinference/model/llm/utils.py, xinference/model/llm/vllm/core.py
=> FEAT: support llama-3 family

xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json
Although both in the official document and config.json, the max length is stated as 65536, however, it is 32768 after actual testing
=> ENH: fix the max length of codeqwen-7B-chat

xinference/model/rerank/core.py
Old reranker model use `sentence_transformers`, only new reranker model use `FlagEmbedding`.
=> BUG: Fix old rerank models use flag rerank issue

xinference/api/restful_api.py, xinference/core/tests/test_restful_api.py
fix bug: https://github.com/xorbitsai/inference/issues/1317#issuecomment-2076828837
=> BUG: no role:user msg or content empty got an error.

xinference/model/llm/llm_family.json
适配https://huggingface.co/berkeley-nest/Starling-LM-7B-alpha 模型
=> FEAT: add Starling model

.pre-commit-config.yaml, xinference/core/supervisor.py, xinference/core/tests/test_worker.py, xinference/core/worker.py, xinference/deploy/utils.py, xinference/device_utils.py, xinference/model/llm/__init__.py, xinference/model/llm/pytorch/deepseek_vl.py, xinference/model/llm/pytorch/tests/test_opt.py, xinference/thirdparty/omnilmm/chat.py, xinference/thirdparty/omnilmm/model/omnilmm.py
Ascend support is tested.
Tested Qwen 7b.
HuggingFace accelerate and timm is imported in OmniLMM, both will cause torch_npu imported which will cause that `ASCEND_RT_VISIBLE_DEVICES` not work, so I put the imports into the functions.
I tested both qwen1.5 and OmniLMM on cuda devices, they work well.
Fixes #1323
=> FEAT: Ascend support

setup.cfg
langchain-community need to be installed separately.
=> BLD: adapt to langchain 0.2.x, which has breaking changes

.gitignore, xinference/deploy/cmdline.py, xinference/model/llm/llm_family.py, xinference/model/llm/memory.py, xinference/model/llm/tests/test_llm_family.py, xinference/model/llm/tests/test_memory_estimate.py
Implement model.llm.memory.estimate_llm_gpu_memory
which output model_mem, kv_cache, overhead, active_mem.
* Download config.json from huggingface/modelscope and load model layers info
* support kv_cache_dtype 8/16/32 (gpu_poor might only calculate fp32)
Algorithm refer to https://github.com/RahulSChand/gpu_poor
model.llm.utils: Add convert_model_size_to_float
```
Usage:
$ env HF_ENDPOINT=https://hf-mirror.com xinference cal-model-mem -s 7 -q Int4 -f gptq -c 16384 -n qwen1.5-chat
model_name: qwen1.5-chat
kv_cache_dtype: 16
model size: 7.0 B
quant: Int4
context: 16384
gpu mem usage:
model mem: 4139 MB
kv_cache: 8192 MB
overhead: 650 MB
active: 17024 MB
total: 30005 MB (30 GB)
$ env HF_ENDPOINT=https://hf-mirror.com xinference cal-model-mem -s 1_8 -q Int4 -f gptq -c 32768 -n qwen1.5-chat …
```
=> FEAT: Add command cal-model-mem

.github/workflows/python.yaml, xinference/core/worker.py
Fixes: https://github.com/xorbitsai/inference/issues/1517
=> BUG: Fix start worker failed due to None device name

xinference/core/__init__.py, xinference/core/supervisor.py, xinference/core/worker.py
It seems not necessary to install ModelActor in xinference.core, 
using original path core.model.ModelActor instead.
=> Correct ModelActor import path in worker & supervisor

xinference/core/chat_interface.py
=> BUG: fix vl-model img path error

doc/source/models/builtin/llm/index.rst, doc/source/models/builtin/llm/telechat.rst, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json
新增中国电信Telecaht大模型，参数量为7B，12B，52B。
其中包含7B和12B的gptq量化模型，int4和int8。
=> FEAT: telechat model

xinference/model/llm/__init__.py, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json, xinference/model/llm/pytorch/core.py, xinference/model/llm/pytorch/minicpmv25.py
https://github.com/xorbitsai/inference/assets/918617/2e40c6e5-6076-449e-9cc2-5fb363f29e48
=> FEAT: new model: mini-cpm-llama3-v-2.5

.github/workflows/python.yaml, xinference/api/restful_api.py, xinference/core/model.py, xinference/core/scheduler.py, xinference/core/tests/test_continuous_batching.py, xinference/deploy/docker/cpu.Dockerfile, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json, xinference/model/llm/pytorch/chatglm.py, xinference/model/llm/pytorch/core.py, xinference/model/llm/pytorch/internlm2.py, xinference/model/llm/pytorch/utils.py
Currently, three models are implemented separately for inference:
- internlm2-chat
- glm
- falcon
1. For falcon, after testing, there is no need to write a single function to handle its inference process. So I delete them.
2. For internlm2-chat, this model is sensitive to the inference parameters like `temperature`, `top_p`, `top_k`. We cannot set them by default if use does not pass these.
3. For glm4,  the inference process lacks the processing of `attention_mask` and `position_ids`, which are very important in glm4 inference. ~~However, glm4's batch inference seems to be problematical. See https://github.com/THUDM/GLM-4/issues/25~~
4. Currently, the `chatglm` series may have issues with duplicate outputs.
=> ENH: Continuous batching supports all the models with `transformers` backend

xinference/core/event.py
chat_completion not response while error appears more than 100 count
```bash
for i in {1..100}
do
curl -i http://localhost:80/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $OPENAI_API_KEY" \
-d '{
"model": "gpt-4",
"max_tokens": "8192",
"messages": [
{"role": "user", "content": "hello"}
]
}'
done
curl -i http://localhost:80/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $OPENAI_API_KEY" \
-d '{
"model": "gpt-4",
"max_tokens": "8192",
"messages": [
{"role": "user", "content": "hello"}
]
}'
```
Note that model must not exists in xinference, and you can use `http://localhost:80/v1/models/gpt-4/events` to see error events.
Fixes #1424 .
=> BUG: chat_completion not response while error appears more than 100

xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/core/model.py, xinference/model/rerank/core.py, xinference/model/rerank/tests/test_rerank.py, xinference/types.py
Added Rerank model token input/output usage with Cohere API compatibility.
Example output:
```
{
"id": "string",
"results": [
{
"document": {
"text": "string"
},
"index": 0,
"relevance_score": 0
}
],
"meta": {
"api_version": None,
"billed_units": None,
"tokens": {
"input_tokens": 0,
"output_tokens": 0
},
"warnings": None
}
}
```
=> FEAT: Add Rerank model token input/output usage

xinference/deploy/utils.py
1. for uvicorn log, the console would not show these logs while the file would remain these.
2. for transformers and vllm log, just remain them on console and file.
=> ENH: Add more log modules

xinference/core/model.py, xinference/core/scheduler.py, xinference/core/tests/test_continuous_batching.py, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json, xinference/model/llm/pytorch/chatglm.py, xinference/model/llm/pytorch/cogvlm2.py, xinference/model/llm/pytorch/core.py, xinference/model/llm/pytorch/glm4v.py, xinference/model/llm/pytorch/qwen_vl.py, xinference/model/llm/pytorch/utils.py
Refactor impl.
Currently supports three multimodal models:
- qwen-vl-chat
- cogvlm2
- glm-4v
=> ENH: Continuous batching supports `vision` model ability

xinference/core/worker.py
```
worker: Add guard for model launching
Because model launching is a long process (download model, loading into GPU).
client might encounter network error in the middle while worker is processing,
add a guard the prevent duplicate operation with the same model_uid.
Provide an rpc call check_model_launch_status() to return LuanchStatus,
to determine whether worker is still working on this model_uid.
```
=> ENH: Add guard for model launching

.github/workflows/python.yaml, doc/source/models/builtin/llm/qwen2-instruct.rst, setup.cfg, xinference/model/llm/__init__.py, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family.py, xinference/model/llm/llm_family_modelscope.json, xinference/model/llm/mlx/__init__.py, xinference/model/llm/mlx/core.py, xinference/model/llm/mlx/tests/__init__.py, xinference/model/llm/mlx/tests/test_mlx.py, xinference/model/llm/utils.py
https://github.com/ml-explore/mlx is developed by Apple to enable AI on Apple silicon chips.
M1 MAX  （qwen2-instruct，7b）
MLX（4-bit） vs. llama.cpp（q4_k_m)
43.3 tokens/s vs. 31.12 tokens/s
=> FEAT: support MLX engine

xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json
Fixes #1750 
This PR added `gemma-2-it`. Some notions:
1. When I ran gguf formats with llama-cpp-python==0.2.81, it crashed, and I can see the gemma-2 format is introduced lately in llama.cpp itself, so I removed gguf formats for now.
2. vllm implemented gemma-2 but it's not released, thus vllm is absent as well.
3. I added MLX format which worked well on my laptop. (Hence this PR replies on #1765 )
=> FEAT: add gemma-2-it

doc/source/models/builtin/llm/chatglm.rst, doc/source/models/builtin/llm/chatglm2.rst, doc/source/models/builtin/llm/chatglm3.rst, doc/source/models/builtin/llm/gemma-2-it.rst, doc/source/models/builtin/llm/glm4-chat-1m.rst, doc/source/models/builtin/llm/glm4-chat.rst, doc/source/models/builtin/llm/index.rst, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json
Now hf has gguf files for both sides, but modelscope only has 9b.
=> ENH: added gguf formats for gemma-2-it

doc/source/models/builtin/llm/index.rst, doc/source/models/builtin/llm/llama-3.1-instruct.rst, doc/source/models/builtin/llm/llama-3.1.rst, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json
**Builtin Model**
- llama 3.1
- llama 3.1 Instruct
**Documents**
- llama 3.1
- llama 3.1 Instruct
=> FEAT: add llama-3.1, llama-3.1-instruct

xinference/model/llm/ggml/llamacpp.py, xinference/model/llm/llm_family.py
#1075 introduced multiple gguf parts, in that PR, the gguf parts were merged into one file, but now llama.cpp will fail to load this file, instead, the llama.cpp could recognize the whole files with given the first part, thus, in this PR, we just symlink the gguf file to the first part, then when loading, we tell llama.cpp the realpath.
Fixes #1912
=> BUG: fix loading multiple gguf parts

xinference/core/worker.py
Bug trigger only on non-local mode:
call `register_model(model_type=flexible)` on worker will raise Exception
File "/opt/inference/xinference/core/worker.py", line 573, in register_model
ValueError: [address=XXXX pid=7] not enough values to unpack (expected 4, got 3)
introduced from
```
commit 9bb548a6d98a7bf145cdbff76ae032aa9ccf9db1
Author: Wang Shenggong [wangshenggong@gmail.com](mailto:wangshenggong@gmail.com)
Date:   Fri Jul 12 11:43:08 2024 +0800
FEAT: Add support for Flexible Model (#1671)
```
=> BUG: fix flexible model register in worker

doc/source/models/builtin/image/kolors.rst, xinference/core/image_interface.py, xinference/model/image/model_spec.json, xinference/model/image/stable_diffusion/core.py
=> FEAT: support kolors image model

xinference/core/model.py, xinference/core/worker.py, xinference/model/llm/vllm/core.py
=> ENH: optimize availability of vLLM

xinference/core/worker.py
Avoid crashing worker on startup process if supervisor is not reachable.
因为__post_create__ 阶段连不上 supervisor 的时候会抛异常 crash, 所以允许在运行阶段重试去连接 supervisor。把 event, status_guard, cache_tracker , add_worker 等都挪到 supervisor 连上之后调用。
Base on PR #2011
=> ENH: [worker] Allow init supervisor_ref lazy

xinference/core/model.py, xinference/model/llm/sglang/core.py, xinference/model/llm/vllm/core.py
Before, we used sglang frontend which does not deliver high throughput, the [new benchmark of sglang](https://lmsys.org/blog/2024-07-25-sglang-llama3/) is based on sglang runtime, thus in this PR we switched to srt.
```
Total time: 38.64 s
Throughput: 0.78 requests/s
Average latency: 38.63 s
Average latency per token: 0.17 s
Average latency per output token: 1.11 s
Throughput: 145.40378699622423 tokens/s
```
```
Total time: 6.02 s
Throughput: 4.98 requests/s
Average latency: 2.44 s
Average latency per token: 0.01 s
Average latency per output token: 0.03 s
Throughput: 959.2033185347453 tokens/s
```
=> ENH: optimize performance of sglang

setup.cfg, xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/constants.py, xinference/core/model.py, xinference/core/supervisor.py, xinference/core/worker.py, xinference/deploy/docker/requirements.txt, xinference/deploy/docker/requirements_cpu.txt, xinference/model/core.py, xinference/model/video/__init__.py, xinference/model/video/core.py, xinference/model/video/diffusers.py, xinference/model/video/model_spec.json, xinference/model/video/model_spec_modelscope.json, xinference/model/video/tests/__init__.py, xinference/model/video/tests/test_diffusers_video.py, xinference/types.py, xinference/web/ui/src/scenes/launch_model/index.js, xinference/web/ui/src/scenes/running_models/index.js
Fixes: https://github.com/xorbitsai/inference/issues/2035
=> FEAT: Support CogVideoX video model

benchmark/benchmark_runner.py, benchmark/benchmark_serving.py
- fix https://github.com/xorbitsai/inference/issues/2111
- Previously, `asyncio.Queue` was created in the `__init__` method rather than in the `run()` function. In lower versions of Python (e.g., 3.9), this could cause the queue to be attached to an incorrect event loop. 
- To address this issue, the creation of the queue has been moved to the warm_up method.
- Additionally, a minor error in a log message has been corrected.
=> BUG: fix asyncio.Queue error in benchmark

xinference/model/embedding/core.py
✅ Closes: #2076
新增嵌入模型dtype参数(目前只支持模型gte-Qwen2,需要模型支持，gte-Qwen2是支持fp16和fp32推理)
=> feat: 🎸 Added the model dtype parameter for embedding (currently only supported for models gte-Qwen2).

xinference/core/worker.py
During worker startup and receive launch_builtin_model concurrently, there were error log:
```
2024-08-20 02:41:08,327 xinference.core.worker 7 ERROR Connected to supervisor as a fresh worker
2024-08-20 02:41:08,327 xinference.core.worker 7 ERROR  Enter launch_builtin_model, args: ... 
2024-08-20 02:41:08,327 xinference.core.worker 7 ERROR report_event error: 'WorkerActor' object has no attribute '_event_collector_ref
```
在 worker重启的同时 launch 模型可能会触发该错误日志.
=> [Bug]: Fix concurrent ops in worker initialization 

doc/source/getting_started/installation.rst
参考: https://github.com/xorbitsai/inference/issues/2206 
修改：统一改为双引号，确保linux和windows环境都能执行成功（单引号在win下执行错误）
pip install 'xinference[sglang]'
——改为 pip install "xinference[sglang]"
pip install 'xinference[mlx]'
——改为：pip install “xinference[mlx]”
=> DOC: Modify the installation documentation to change single quotes to double quotes for Windows compatibility.

xinference/api/restful_api.py, xinference/conftest.py, xinference/core/cache_tracker.py, xinference/core/event.py, xinference/core/model.py, xinference/core/status_guard.py, xinference/core/supervisor.py, xinference/core/tests/test_metrics.py, xinference/core/tests/test_worker.py, xinference/core/worker.py, xinference/deploy/local.py, xinference/deploy/supervisor.py, xinference/deploy/utils.py, xinference/deploy/worker.py
Fixes https://github.com/xorbitsai/xoscar/issues/103
The reason is because these actors use `uid()` to generate default uid, which override the `xoscar.Actor`'s `uid` property, hence change them to `default_uid()`.
=> BUG: use `default_uid` to replace `uid` of actors which may override the xoscar actor's uid property

.github/workflows/python.yaml, setup.cfg, xinference/deploy/docker/requirements.txt, xinference/deploy/docker/requirements_cpu.txt, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json
Testing has been done locally and the model requires the following two dependencies to be added - datamodel_code_generator and jsonschema
=> FEAT: Support minicpm-4B

benchmark/README.md, benchmark/benchmark_latency.py, benchmark/benchmark_long.py, benchmark/benchmark_rerank.py, benchmark/benchmark_runner.py, benchmark/benchmark_serving.py
1. Added the `--print-error` option to benchmarking tools to improve error diagnostics:
- If an error occurs, the system prompts:`INFO:benchmark_runner: Errors were encountered. Use --print-error for details.`.
- When used, --print-error provides a detailed traceback for errors: `INFO:benchmark_runner: Error for prompt length 182: xxx`.
2. Updated README.md.
=> ENH: add `print-error` option in benchmark

xinference/api/restful_api.py, xinference/core/image_interface.py, xinference/model/image/stable_diffusion/core.py
`/sdapi/sd-models` and `sdapi/samplers` are used in dify stable diffusion tool thus we add the API first.
=> FEAT: support sdapi/sd-models and sdapi/samplers

xinference/model/audio/whisper.py
**Reason:**
The `openai/whisper` model provides weights in the `.safetensors` format, but the `xinference`-supported `BELLE-2/Belle-whisper-large-v3-zh` model only provides weights in the `pytorch_model.bin` format. Setting `use_safetensors=True` causes errors when running the `Belle-whisper-large-v3-zh` model.
**Solution:**
Added a check to determine if `.safetensors` files are present in the model directory.
**Effect:**
Both `whisper` and `Belle-whisper` models now launch and inference correctly on our company's private server.
=> BUG: fix issue with model launch failing when .safetensors file is missing (#2094)

.github/workflows/python.yaml, xinference/model/image/model_spec.json, xinference/model/image/model_spec_modelscope.json, xinference/model/image/stable_diffusion/core.py
This feature requires installation of diffusers from source code.
=> FEAT: support flux.1 image2image and inpainting

xinference/model/audio/cosyvoice.py
=> BUG: Fix CosyVoice missing output

setup.cfg, xinference/deploy/docker/requirements.txt, xinference/model/image/stable_diffusion/core.py
If package "deepcache" is installed,turn on deepcache optimization by default, which brings 2x speedup.
The feature can be turned off by option 'deepcache=False'.
deepcache & cpu_offloading is tested.
=> FEAT: Support deepcache with sd models

xinference/model/llm/vllm/core.py
When I launch the LLM Qwen2.5-Instruct with vLLM backend on xinference,  through built-in model or just create another custom model, and try it on a relative long context, from the log on standard output, the backend says:
> Input prompt (xxxx tokens) is too long and exceeds limit of 4096
and the it just returns an empty response to the request from OpenAI API. 
However, when serving the model directly with vLLM, using default engine arguments, it just works fine.
For the argument max-model-len, referencing https://docs.vllm.ai/en/latest/models/engine_args.html:
>  If unspecified, will be automatically derived from the model config.
The current version of xinference code use a specific default value 4096 for argument max-model-len passed to vLLM backend, and override the auto-selected …
=> BUG: Fix default value of max_model_len for vLLM backend.

xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/core/image_interface.py, xinference/core/model.py, xinference/core/progress_tracker.py, xinference/core/supervisor.py, xinference/core/tests/test_progressor.py, xinference/core/worker.py, xinference/model/image/sdapi.py, xinference/model/image/stable_diffusion/core.py, xinference/model/image/tests/test_stable_diffusion.py, xinference/model/llm/transformers/tests/test_opt.py
Text to image:
https://github.com/user-attachments/assets/5a4937a9-d8e6-4067-99f6-dd5e78479b97
Image to image:
https://github.com/user-attachments/assets/8fd22943-eb42-44d8-8e0f-3d77ea0dab00
=> FEAT: support getting progress for image model

xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json, xinference/model/llm/transformers/cogvlm2.py, xinference/model/llm/transformers/cogvlm2_video.py, xinference/model/llm/transformers/deepseek_vl.py, xinference/model/llm/transformers/glm4v.py, xinference/model/llm/transformers/intern_vl.py, xinference/model/llm/transformers/minicpmv25.py, xinference/model/llm/transformers/minicpmv26.py, xinference/model/llm/transformers/omnilmm.py, xinference/model/llm/transformers/qwen2_audio.py, xinference/model/llm/transformers/qwen2_vl.py, xinference/model/llm/transformers/qwen_vl.py, xinference/model/llm/transformers/utils.py, xinference/model/llm/transformers/yi_vl.py, xinference/model/llm/utils.py, xinference/model/llm/vllm/core.py, xinference/model/llm/vllm/utils.py
=> FEAT: support qwenvl2 vllm engine

xinference/__init__.py, xinference/deploy/supervisor.py, xinference/model/__init__.py, xinference/utils.py
Avoid installing model in app level
This will speed up cli and simplify dependency for distributed deployment
Move install model from xinference/__init__.py to to xinference/model/__init__.py
cli 在import xinference 的时候默认会运行 models/__init__.py 中的 install,  导致加载 torch 然后遍历所有 model，花时间很多, 但实际对于命令行并不需要. 
修改前：
```
time xinference list
real    0m6.322s
user    0m6.187s
sys     0m0.769s
```
修改后:
```
real    0m0.793s
user    0m1.164s
sys     0m0.268s
```
已经测试过模型启动一切正常, 聊天也正常
=> ENH: Speed up cli interaction

xinference/deploy/supervisor.py
由于有反馈说 xinference-local 变慢。
在 PR #2443 修改了 model install 的方式, 没注意到  deploy/supervisor.py 里面有一个显式的重复调用，现在移除。
实测确认无论改还是不改，实际 xinference/model/__init__.py 的 _install 方法都只会执行一次,  即使把PR #2443 revert, xinference-local的启动速度也并无明显差别。
Fixes #2460 .
=> Remove duplicated call of model_install

.github/workflows/python.yaml, setup.cfg, xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/core/model.py, xinference/deploy/docker/requirements.txt, xinference/deploy/docker/requirements_cpu.txt, xinference/model/image/core.py, xinference/model/image/model_spec.json, xinference/model/image/model_spec_modelscope.json, xinference/model/image/ocr/__init__.py, xinference/model/image/ocr/got_ocr2.py, xinference/model/image/tests/test_got_ocr2.py
Fixes: https://github.com/xorbitsai/inference/issues/2452 
Fixes: https://github.com/xorbitsai/inference/issues/2441
=> FEAT: Support GOT-OCR2_0

doc/source/models/builtin/embedding/gte-qwen2.rst, xinference/model/embedding/model_spec.json
Fixes #2471 
fix embedding model gte-Qwen2 dimensions
> wrong dimensions：
> 
> https://github.com/xorbitsai/inference/blob/48a07e8af3d015908c8a55f91c7baea3afbbb809/xinference/model/embedding/model_spec.json#L236C1-L237C1
> 
> correct dimensions：
> 
> https://github.com/xorbitsai/inference/blob/48a07e8af3d015908c8a55f91c7baea3afbbb809/xinference/model/embedding/model_spec_modelscope.json#L238
base on the right message：
https://huggingface.co/Alibaba-NLP/gte-Qwen1.5-7B-instruct
https://modelscope.cn/models/iic/gte_Qwen1.5-7B-instruct/summary
=> BUG: fix embedding model gte-Qwen2 dimensions

xinference/client/tests/test_client.py, xinference/core/model.py, xinference/core/tests/test_model.py
=> ENH: Pending queue for concurrent requests

.github/workflows/docker-cd.yaml, .github/workflows/python.yaml, pyproject.toml, setup.cfg, xinference/core/tests/test_continuous_batching.py, xinference/model/rerank/core.py
The return value of compute_score() in the bge-reranker-v2-minicpm-layerwise model is a two-dimensional array. Currently, an error message `only integer scalar arrays can be converted to a scalar index` is reported during execution, so additional processing is required
=> BUG: fix bge-reranker-v2-minicpm-layerwise rerank issue

xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/model/rerank/core.py, xinference/model/rerank/tests/test_rerank.py
The current Rerank model return value is not normalized. FlagEmbedding provides a normalization option. It is recommended to return the normalized value.
=> ENH: add normalize to rerank model

doc/source/models/model_abilities/audio.rst, xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/model/audio/fish_speech.py, xinference/model/audio/tests/test_fish_speech.py
- Fixes: https://github.com/xorbitsai/inference/issues/2532
=> ENH: Support fish speech reference audio

doc/source/models/builtin/llm/codestral-v0.1.rst, xinference/model/llm/llm_family.json
Updated the URI and documentation for Codestral v0.1, changed from Mistral-7B-Instruct-v0.2 to Codestral-22B-v0.1 for the pytorch format.
Fixes https://github.com/xorbitsai/inference/issues/2588
=> BUG: Fix Codestral v0.1 URI for Pytorch Format

xinference/_compat.py, xinference/api/restful_api.py, xinference/model/llm/vllm/core.py
Support Guided Decoding for vllm async engine
waiting for vllm release, a version bump is needed.
https://github.com/xorbitsai/inference/issues/1562
https://github.com/vllm-project/vllm/pull/8252
=> feat: support guided decoding for vllm async engine

xinference/deploy/cmdline.py, xinference/deploy/test/test_cmdline.py
issue： [# 2539](https://github.com/xorbitsai/inference/issues/2539)
More information is provided for the situation described in issue (#2539), and a test example is added to ensure that the error parameters of the test message are correct
Problem description:
1. When a user specifies a parameter but does not specify the parameter value, the error message is not obvious
2. After investigation, it is found that the problem is the 'click' library of the parsing parameter passed, and the parameter name that indicates the value of the next parameter is taken as the parameter value
Solution:
- Adds an error message and indicates the location of the parameter passing error
=> ENH: Optimize error message when user parameters are passed incorrectly

xinference/model/embedding/core.py
#2540 introduces `FlagEmbedding` package to support sparse vector for bge-m3. However, `FlagEmbedding` is an optional dependency for embedding model (but required for rerank):
https://github.com/xorbitsai/inference/blob/70a008138be7fa13706964124d342f194f7f584d/setup.cfg#L184-L187
In the case `FlagEmbedding` is not installed, an `ImportError` will be raised even if embedding models only based on `sentence-transformers` are used, due to the logic related to `BGEM3FlagModel`. This PR fixes this problem.
By the way, maybe adding `FlagEmbedding` to required dependency for embedding is not suitable now until upstream solve the dependency, since it requires `transformers==4.44.2`(https://github.com/FlagOpen/FlagEmbedding/blob/master/setup.py#L18) and will make models like Qwen2-VL unusable …
=> BUG: fix ImportError when optional dependency FlagEmbedding is not installed

xinference/api/restful_api.py, xinference/model/llm/vllm/core.py
Update `api/restful_api.py` and `model/llm/vllm/core.py` to pass through sampling parameter `skip_special_tokens`.
Fixes #2656 .
=> ENH: bypass the sampling parameter skip_special_tokens to vLLM backend

.github/workflows/python.yaml, xinference/deploy/docker/cpu.Dockerfile, xinference/model/llm/transformers/utils.py
Fixes #2556 
Here's the effect after fixing.
=> BUG: `stop` parameter leads to failure with `transformers` backend

xinference/_compat.py, xinference/api/restful_api.py
FIX: https://github.com/xorbitsai/inference/issues/2636
also https://github.com/xorbitsai/inference/issues/2620
cc @qinxuye 
```python
client = openai.Client(api_key="not empty", base_url="http://127.0.0.1:9997/v1")
class TSchema(BaseModel):
test: str
num: int
schema = TSchema.model_json_schema()
messages = [
{"role": "system", "content": "you are a helpful assistant"},
{"role": "user", "content": "give me an example json, fill a random number"}
]
completion = client.chat.completions.create(
model="qwen2-instruct",
messages = messages,
extra_body={
"guided_json": schema,
"guided_decoding_backend": "outlines"
})
```
Output:
```
{ "test": "Example JSON", "num": 42 }
```
Guided Choice also works fine.
=> ENH: Guided Decoding OpenAIClient compatibility

xinference/model/llm/mlx/core.py, xinference/model/llm/mlx/tests/test_mlx.py
Before, VLM model must have images for MLX-vlm. This PR addresses this issue.
=> ENH: support no images for MLX vlm

xinference/model/llm/vllm/core.py
since version 0.6.3, the AsyncLLMEngine in vllm supports priority scheduling (https://github.com/vllm-project/vllm/pull/8850)，so add a new parameter "scheduling-policy" for the vllm model config to support priority scheduling.
=> FEAT: support scheduling-policy for vllm

doc/source/getting_started/installation.rst, doc/source/models/builtin/llm/index.rst, doc/source/models/builtin/llm/minicpm3-4b.rst, doc/source/models/builtin/llm/qvq-72b-preview.rst, doc/source/models/builtin/video/hunyuanvideo.rst, doc/source/models/builtin/video/index.rst, doc/source/user_guide/backends.rst, xinference/model/video/diffusers.py, xinference/model/video/model_spec.json
I ran on a 48GB GPU. Loading model with CPU offload, or OOM will occur even for 320x512 resolusion.
Loading model:
```
xinference launch --model-name HunyuanVideo --model-type video --cpu_offload True
```
Inference:
```
from xinference.client import Client
client = Client("http://127.0.0.1:9997")
model = client.get_model("HunyuanVideo")
input_text = "A cat walks on the grass, realistic"
resp = model.text_to_video(input_text, height=320, width=512, num_frames=61, num_inference_steps=30)
b64_video = resp['data'][0]['b64_json']
video_bytes = base64.b64decode(b64_video)
with open('1.mp4', 'wb') as f:
f.write(video_bytes)
```
Result:
https://github.com/user-attachments/assets/fafe6e9c-343c-48b7-8a7d-9e77a113d99b
=> FEAT: support HunyuanVideo

xinference/api/restful_api.py, xinference/model/llm/__init__.py, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json, xinference/model/llm/transformers/cogagent.py, xinference/model/llm/transformers/core.py, xinference/model/llm/utils.py, xinference/types.py
=> FEAT: Support cogagent-9b

xinference/model/audio/whisper.py
The current implementation has fixed Whisper pipeline parameters that are not suitable for all use cases. This pull request allows the specification of parameters during model launch.
=> ENH: add model config for Whisper

xinference/model/llm/utils.py, xinference/model/llm/vllm/core.py
As described in #2659 the Cline extension uses a specific messages format.
#2734 supports cline for vLLM engine.
This PR applies it to all other engines.
Test on windows+transformers is success.
=> ENH: support cline style messages for all backend engines

doc/source/locale/zh_CN/LC_MESSAGES/user_guide/vllm_enhancement.po, doc/source/user_guide/vllm_enhancement.rst, xinference/core/model.py, xinference/core/supervisor.py, xinference/core/worker.py, xinference/model/llm/memory.py, xinference/model/llm/vllm/xavier/block.py, xinference/model/llm/vllm/xavier/block_tracker.py, xinference/model/llm/vllm/xavier/collective.py, xinference/model/llm/vllm/xavier/collective_manager.py, xinference/model/llm/vllm/xavier/executor.py, xinference/model/llm/vllm/xavier/scheduler.py, xinference/model/llm/vllm/xavier/test/test_xavier.py, xinference/model/llm/vllm/xavier/transfer.py
1. Xavier supports model recovery. Due to the special nature of rank 0, a separate, simple model actor is created for rank 0. This actor is responsible only for constructing the collective communication world. A new role, `collective_manager`, is introduced. In the recovery logic, the `collective_manager` instructs all ranks to reconstruct the collective communication world.
2. If an error occurs during the transmission process (e.g., the sender is undergoing recovery), vllm's scheduling supports rollback, where it reverts to forcing computation instead of transmission.
3. Xavier's transmission process only applies to the PREFILL stage, and no data transmission occurs during the DECODE stage. This is because data transmission in the DECODE stage only affects the last token of a block when …
=> ENH: Some improvements for Xavier

.github/workflows/python.yaml, README.md, README_zh_CN.md, setup.cfg, xinference/deploy/docker/requirements.txt, xinference/deploy/docker/requirements_cpu.txt, xinference/model/llm/llama_cpp/core.py, xinference/model/llm/llm_family.py, xinference/model/llm/llm_family_modelscope.json
This PR fixed a few bugs:
1. Some model has GGUF with multiple parts and single file at the same time, e.g. for qwen2.5-instruct 7b, `q4_k_m` has two files, meanwhile `q3_k_m` has only one file, before this PR, when loading `q3_k_m`, the downloading of GGUF file will be skipped.
2. Fixes model_path for `llama.cpp` engine, before the path will be treated as a dir.
=> BUG: fix llama-cpp when some quantizations have multiple parts

doc/source/models/builtin/llm/index.rst, doc/source/models/builtin/llm/qwen2.5-vl-instruct.rst, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json, xinference/model/llm/transformers/core.py, xinference/model/llm/transformers/qwen2_vl.py
For now, transformers needs to be installed from source code:
```
pip install git+https://github.com/huggingface/transformers.git
```
vllm not supported yet.
https://github.com/user-attachments/assets/ff2fe0a7-a215-48d2-bdaa-5a102af0a8d6
=> FEAT: support qwen2.5-vl-instruct

doc/source/getting_started/installation.rst, doc/source/models/builtin/llm/deepseek-r1-distill-llama.rst, doc/source/models/builtin/llm/index.rst, doc/source/models/model_abilities/tools.rst, doc/source/user_guide/backends.rst, xinference/api/restful_api.py, xinference/model/llm/llama_cpp/core.py, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json, xinference/model/llm/mlx/core.py, xinference/model/llm/transformers/core.py, xinference/model/llm/utils.py, xinference/model/llm/vllm/core.py
This PR added deepseek-r1-distill-llama, including 8b and 70b and various formats.
Function calling is implemented according to chat template, but the result is very unstable, and currently the parsing logic for tools result might be wrong.
=> FEAT: support deepseek-r1-distill-llama

doc/source/models/model_abilities/multimodal.rst, doc/source/models/model_abilities/rerank.rst
Fixes a couple of typos on rerank.rst and multimodal.rst, notably on line 157 and line 46.
=> DOC: Fix a couple of typos

doc/source/locale/zh_CN/LC_MESSAGES/user_guide/vllm_enhancement.po, doc/source/user_guide/vllm_enhancement.rst, setup.cfg, xinference/deploy/docker/requirements.txt, xinference/model/llm/vllm/xavier/executor.py, xinference/model/llm/vllm/xavier/scheduler.py
1. Xavier now supports `vLLM >= 0.7.0`, drops support for older versions
2. Fixes #2866 
3. About pynvml >= 12: See https://github.com/vllm-project/vllm/issues/12947
=> CHORE: Xavier now supports `vLLM >= 0.7.0`, drops support for older versions

xinference/core/model.py, xinference/core/status_guard.py, xinference/core/supervisor.py, xinference/core/worker.py, xinference/model/llm/sglang/core.py
With this PR, now deepseek-r1 FP8 can run on 2 8xH100/H20 workers.
To use this feature, launch model with extra param: n_worker: 2.
Web UI will add this option soon, command line needs to be updates as well.
=> FEAT: support distributed inference for sglang

xinference/model/image/stable_diffusion/core.py
=> BUG: fix FLUX when a scheduler is specified which is incompatible.

xinference/client/restful/restful_client.py, xinference/deploy/cmdline.py, xinference/deploy/test/test_cmdline.py
This PR polished cmdline, added `--n-worker` to support distributed inference, and added `--model-path` which treats model_path as builtin option, meanwhile, makes sure that `--model_path` can work as well.
=> ENH: cmdline supports --n-worker, add --model-path and make it compatible with --model_path

xinference/deploy/docker/Dockerfile, xinference/deploy/docker/cpu.Dockerfile
Fixes #2929 
Add ffmpeg 6.1 installation through Conda (only for FFmpeg, not replacing system Python) in Dockerfile.
=> BLD: Install ffmpeg 6 for audio & video models

xinference/model/llm/transformers/utils.py
BUG: fix Error while using Langchain Chatchat ，because The parameter [max_tokens] passed is None
Fixes https://github.com/xorbitsai/inference/issues/2559
=> BUG: fix Error while using Langchain-chatchat, because the parameter [max_tokens] passed is None

xinference/model/embedding/core.py
=> BUG: wrong kwargs passing to encode method when using jina-clip-v2

.github/workflows/python.yaml, setup.cfg, xinference/client/tests/test_client.py, xinference/conftest.py, xinference/core/model.py, xinference/core/tests/test_restful_api.py, xinference/core/worker.py, xinference/deploy/docker/Dockerfile, xinference/deploy/docker/cpu.Dockerfile, xinference/model/llm/__init__.py, xinference/model/llm/llama_cpp/core.py, xinference/types.py
Disabled by default, can be enabled by setting env `USE_XLLAMACPP=1`
=> ENH: Support xllamacpp

xinference/model/rerank/core.py
An error occurs when assigning an instance of `_ModelWrapper` to a sub-module in a PyTorch model:
```
TypeError: cannot assign '_ModelWrapper' as child module 'model'; (torch.nn.Module or None expected)
```
PyTorch requires all sub-modules to inherit from `nn.Module`, but the original implementation of `_ModelWrapper` does not.
- Have `_ModelWrapper` class inherit from `nn.Module`
- Call `super().__init__()` in the constructor
- Rename the existing `__call__` method to conform with PyTorch’s standard naming convention, which is called `forward`
The modifications are minimal and do not introduce any further changes beyond necessary adjustments for compatibility.
- The original TypeError no longer appears after reloading the model  
- The model runs as expected, and the logic of counting …
=> BUG: Fix PyTorch TypeError: Make _ModelWrapper Inherit from nn.Module

setup.cfg, xinference/deploy/docker/requirements.txt, xinference/deploy/docker/requirements_cpu.txt
auto-gptq is not maintained, gptqmodel is way more faster and still under development. 
Transformers has integrated gptqmodel as well, thus no code needs to be modified.
=> BLD: use gptqmodel to replace auto-gptq

xinference/client/tests/test_client.py, xinference/model/llm/llama_cpp/core.py, xinference/model/llm/reasoning_parser.py, xinference/model/llm/utils.py
1. Modify xinference/client/tests/test_client.py: For chunk where finish_reason is not None, assert that delta = {"content": ""}.
2. Modify xinference/model/llm/llama_cpp/core.py: Filter out keys in the returned results that do not belong to ChatCompletionChunk.
3. Modify xinference/model/llm/reasoning_parser.py: Fix the issue where both reasoning_content="" and content="".
4. Modify xinference/model/llm/utils.py:  Ensure that chunk with finish_reason not being None includes values for both content and reasoning_content.
=> BUG: fix llm stream response

xinference/model/llm/__init__.py, xinference/model/llm/llm_family.py, xinference/model/llm/transformers/__init__.py, xinference/model/llm/transformers/core.py, xinference/model/llm/transformers/intern_vl.py, xinference/model/llm/transformers/qwen2_vl.py
define two decorators for self registering only in new model code file, keep codes loose coupling
=> REF: simplify transformers model registration with decorators.

pyproject.toml
See https://github.com/pypa/wheel/issues/662
From day 1 we limited setuptools for bdist_wheel, setuptools accepted this command in a newer version, thus remove the limitation.
=> BLD: remove setuptools limitation in project.toml

xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/core/progress_tracker.py, xinference/core/supervisor.py, xinference/core/tests/test_restful_api.py, xinference/core/worker.py, xinference/deploy/cmdline.py, xinference/model/tests/__init__.py, xinference/model/tests/test_utils.py, xinference/model/utils.py, xinference/utils.py
This PR basically did two things:
1. Support getting progress when launching models
2. Support cancelling when downloading.
This main idea is to patch `tqdm.update`. All the hub libraries like huggingface_hub and modelscope all used tqdm as progress bar vendor. Important part is to identify which tqdm is the main progress( like downloading 11 files) and the file progress(for a file 300M of 500M downloaded), the progress is calculated from them. Further more, when user cancels the launching, the downloader will know and raise error in `tqdm.update`, thus the downloading can be cancelled as expected.
This PR only supports command lines, web UI needs to adapt new APIs about getting progress and cancelling.
Demo:
https://github.com/user-attachments/assets/99905b25-33d3-4e57-b8df-4027377aba3b
=> FEAT: support getting download progress and cancel download

xinference/model/llm/transformers/gemma3.py, xinference/model/llm/transformers/minicpmv26.py, xinference/model/llm/transformers/qwen2_vl.py, xinference/model/llm/vllm/core.py, xinference/types.py, xinference/web/ui/src/scenes/launch_model/data/data.js
Support VLLM and Transformers pass min/max_pixels params for qwen2.5-vl/gemma3/minicpm2.6
Transformers/VLLM：：
> max_pixels=1003520
> min_pixels=200704
>
=> FEAT: support min/max_pixels params for vision model

setup.cfg, xinference/core/chat_interface.py, xinference/deploy/docker/requirements.txt, xinference/deploy/docker/requirements_cpu.txt, xinference/model/llm/llm_family.json, xinference/model/llm/llm_family.py, xinference/model/llm/llm_family_modelscope.json, xinference/model/llm/transformers/qwen-omni.py, xinference/model/llm/transformers/qwen2_audio.py, xinference/model/llm/utils.py, xinference/types.py
=> FEAT: support qwen2.5-omni

doc/source/locale/zh_CN/LC_MESSAGES/models/virtualenv.po, doc/source/models/builtin/video/index.rst, doc/source/models/builtin/video/wan2.1-1.3b.rst, doc/source/models/builtin/video/wan2.1-14b.rst, doc/source/models/virtualenv.rst, xinference/model/video/diffusers.py, xinference/model/video/model_spec.json, xinference/model/video/model_spec_modelscope.json
```python
import base64
prompt = "A cat walks on the grass, realistic"
negative_prompt = "Bright tones, overexposed, static, blurred details, subtitles, style, works, paintings, images, static, overall gray, worst quality, low quality, JPEG compression residue, ugly, incomplete, extra fingers, poorly drawn hands, poorly drawn faces, deformed, disfigured, misshapen limbs, fused fingers, still picture, messy background, three legs, many people in the background, walking backwards"
model = client.get_model('Wan2.1-1.3B')
resp = model.text_to_video(
prompt=prompt,
negative_prompt=negative_prompt,
height=480,
width=832,
num_frames=81,
guidance_scale=5.0,
fps=15
)
b64_video = resp['data'][0]['b64_json']
video_bytes = base64.b64decode(b64_video)
with open('wan.mp4', 'wb') as f: …
```
=> FEAT: Wan 2.1 text2video

xinference/model/llm/__init__.py, xinference/model/llm/llm_family.py, xinference/model/llm/vllm/core.py
Add ggufv2 support for vLLM. 
A 671B Deepseek-R1 model from [here](https://huggingface.co/unsloth/DeepSeek-R1-GGUF/tree/main/DeepSeek-R1-UD-Q2_K_XL) has been tested.
Due to limitation from vLLM, currently only supports single gguf model (merge by llama.cpp's tool) and requires loading config and tokenizer from config files. More details can be found in [here](https://github.com/vllm-project/vllm/pull/13167).
The testing config is attached below.
Note that this feature will be available only when vllm>=0.8.2, thus requires manual update of vllm.
=> FEAT: add ggufv2 support for vLLM

doc/source/getting_started/troubleshooting.rst, doc/source/locale/zh_CN/LC_MESSAGES/getting_started/troubleshooting.po
https://github.com/vllm-project/vllm/issues/10759
Model architectures ['Qwen2ForCausalLM'] failed to be inspected. Please check the logs for more details.
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp-a34b3233.so.1 library...
=> DOC: update troubleshooting.rst for the launch error caused by numpy

xinference/core/supervisor.py
When model loads in a thread, e.g vllm xinf distributed executor, when loading failed which raised in `wait_for_load`, the worker status is not recorded yet, thus the `terminate_model` will skip, resources is occupied on workers already, this PR fixed it.
=> BUG: fix failure of clearing resources when loading model failed

doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/video.po, doc/source/models/builtin/video/index.rst, doc/source/models/builtin/video/wan2.1-i2v-14b-480p.rst, doc/source/models/builtin/video/wan2.1-i2v-14b-720p.rst, doc/source/models/model_abilities/video.rst, xinference/api/restful_api.py, xinference/client/restful/restful_client.py, xinference/core/model.py, xinference/model/video/diffusers.py, xinference/model/video/model_spec.json, xinference/model/video/model_spec_modelscope.json
This PR added `image_to_video` support.
```
import base64
import io
from xinference.client import Client
from diffusers.utils import load_image
model = client.get_model('Wan2.1-i2v-14B-480p')
image = load_image("https://hf-mirror.com/datasets/huggingface/documentation-images/resolve/main/diffusers/astronaut.jpg")
prompt = (
"An astronaut hatching from an egg, on the surface of the moon, the darkness and depth of space realised in "
"the background. High quality, ultrarealistic detail and breath-taking movie-like camera shot."
)
negative_prompt = "Bright tones, overexposed, static, blurred details, subtitles, style, works, paintings, images, static, overall gray, worst quality, low quality, JPEG compression residue, ugly, incomplete, extra fingers, poorly drawn hands, poorly drawn faces, …
```
=> FEAT: support image_to_video

doc/source/locale/zh_CN/LC_MESSAGES/models/virtualenv.po, doc/source/models/virtualenv.rst, setup.cfg, xinference/core/worker.py, xinference/deploy/docker/requirements-base.txt, xinference/deploy/docker/requirements.txt, xinference/deploy/docker/requirements_cpu-base.txt, xinference/deploy/docker/requirements_cpu.txt, xinference/deploy/utils.py, xinference/model/llm/transformers/qwen-omni.py, xinference/model/llm/vllm/tests/test_distributed_executor.py, xinference/model/llm/vllm/xavier/test/test_xavier.py
Requires: https://github.com/xorbitsai/xoscar/pull/134
=> ENH: Worker env isolation

xinference/core/model.py
`gc.collect` may hang due to unknown reason, thus put it into thread to prevent from hanging the entire event loop.
=> BUG: fix potential stop hang

setup.cfg, xinference/core/model.py, xinference/core/worker.py, xinference/deploy/docker/requirements-base.txt, xinference/deploy/docker/requirements.txt, xinference/deploy/docker/requirements_cpu-base.txt, xinference/deploy/docker/requirements_cpu.txt
This PR reverts #3434  , as mentioned in https://github.com/xorbitsai/xoscar/pull/140 , xoscar introduced `wait_for` API to solve the issue that `asyncio.wait_for` cannot raise timeout for xoscar actor call.
=> FEAT: use xo.wait_for instead of asyncio.wait_for for actor call

xinference/model/llm/llm_family.json, xinference/model/llm/llm_family_modelscope.json
Use Qwen's official quantitative model repository
of which
GPTQ-Int8 quantization model for Qwen3-0.6B/Qwen3-1.7B
AWQ quantization model for Qwen3-4B/Qwen3-8B/Qwen3-14B/Qwen3-32B
GPTQ-Int4 quantization model for Qwen3-30B-A3B/Qwen3-235B-A22B
Due to the incomplete official GGUF format, GGUF still uses the quantization model provided by unsloth
=> ENH: Use Qwen's official quantitative model repository

xinference/core/model.py
- before
- after
curl -X 'POST' 'http://192.168.1.33:9997/v1/audio/transcriptions' \
-H 'accept: application/json' \
-H "Content-Type: multipart/form-data" \
-F file="@./chinese_test.wav" \
-F 'kwargs={"use_itn":false}' \
-F model="SenseVoiceSmall"
We can pass extra arguments via kwargs
Closes https://github.com/xorbitsai/inference/issues/2075
Closes https://github.com/xorbitsai/inference/issues/3497
=> ENH: pass extra arguments for speech2text API.

xinference/core/tests/test_worker.py, xinference/core/worker.py
closes #1848 #2260 #2708 #3041
In the current implementation, after a user deploys a vLLM model, it is not possible to deploy another model using the same GPU. In particular, if you deploy a vLLM model to a specific device by setting the `--gpu_memory_utilization` parameter to a small value, an error in Xinference will stop the launch, even though the model can actually be launched in the remaining memory. This is unnatural behavior considering that, for example, you can deploy a vLLM model on the same GPU after deploying a Transformers model (the result is the same, but the order of deployment changes whether it can be deployed or not).
In this PR, we have removed this error only when the user specifies the GPU ID. This allows advanced users who want to launch multiple models on the same …
=> ENH: remove check when specified GPU index for vllm

xinference/model/audio/model_spec.json, xinference/model/audio/model_spec_modelscope.json
https://www.modelscope.cn/models/iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary
SeACoParaformer是阿里巴巴语音实验室提出的新一代热词定制化非自回归语音识别模型。相比于上一代基于CLAS的热词定制化方案，SeACoParaformer解耦了热词模块与ASR模型，通过后验概率融合的方式进行热词激励，使激励过程可见可控，并且热词召回率显著提升。
=> FEAT: SeACoParaformer model

xinference/client/restful/restful_client.py
We can pass some non-standard arguments to models if we need.
```
from xinference.client import Client
client = Client("http://192.168.1.33:9997")
model = client.get_model("seaco-paraformer-zh")
with open("asr_example.wav", "rb") as audio_file:
audio = audio_file.read()
res=model.transcriptions(audio)
print(res)
res=model.transcriptions(audio,hotword="小艾 魔搭")  #hotword  热词传递
print(res)
model = client.get_model("SenseVoiceSmall")
with open("gaoli_20230611103808.wav", "rb") as audio_file:
audio = audio_file.read()
res=model.transcriptions(audio)
print(res)
res=model.transcriptions(audio,use_itn=False)  #use_itn  逆文本正则化关闭
print(res)
```
```
{'text': '欢迎大家来到么哒社区进行体验。'}
{'text': '欢迎大家来到魔搭社区进行体验。'}
{'text': '少全支付模式境内外支付创新无主。如意金条是中国工商银行发行的实物黄金产品，工行品质实力铸就AU999.9黄金铸造，自身具有商品属性和货币属性，可投资也可收藏，品牌标识质量保障， …
```
=> FEAT: add kwargs for transripts client API

xinference/model/rerank/core.py, xinference/model/rerank/model_spec.json, xinference/model/rerank/model_spec_modelscope.json, xinference/model/rerank/utils.py
Fixes #3583 
Fixes #3578 
Fixes #3596
=> FEAT: support qwen3-reranker

xinference/model/embedding/sentence_transformers/core.py, xinference/model/rerank/core.py
Now for qwen3 embedding & rerank, `flash_attn2` will be detected and set once it's installed, however, when users have limited resource, some layers may be offloaded because we specified `device_map=auto`, hence, in this PR, we added a `enable_flash_attn` option, when off, the flash_attn will not be used.
Fixes #3638
=> ENH: add `enable_flash_attn` param for loading qwen3 embedding & rerank

xinference/deploy/local.py
fix: (xinference) C:\Windows\System32>xinference-local --host 127.0.0.1 -p 9997
Traceback (most recent call last):
File "C:\tools\anaconda3\envs\xinference\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\tools\anaconda3\envs\xinference\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "C:\tools\anaconda3\envs\xinference\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
sys.exit(local())
File "C:\tools\anaconda3\envs\xinference\lib\site-packages\click\core.py", line 1161, in __call__
return self.main(*args, **kwargs)
File "C:\tools\anaconda3\envs\xinference\lib\site-packages\click\core.py", line 1082, in main
rv = self.invoke(ctx)
File "C:\tools\anaconda3\envs\xinference\lib\site-packages\click\core.py", line …
=> ENH: improve local cluster startup reliability via child-process readiness signaling

xinference/model/embedding/sentence_transformers/core.py, xinference/model/rerank/core.py
Fixes #3732
When flash_attn installed and CPU specified, the error will show `FlashAttention2 has been toggled on, but it cannot be used due to the following error: Flash Attention 2 is not available on CPU. Please make sure torch can access a CUDA device. `.
In this PR, flash_attn is disabled if no cuda available even it's installed.
=> BUG: disable flash_attn for qwen3 embedding & rerank when no gpu available

xinference/core/chat_interface.py, xinference/model/llm/llm_family.json, xinference/model/llm/transformers/multimodal/glm4_1v.py, xinference/model/llm/vllm/core.py
=> FEAT: [model] support glm-4.1v-thinking

xinference/model/rerank/core.py
This PR updates the decorator from @torch.no_grad() to @torch.inference_mode() in the Qwen3-Reranker implementation.
torch.inference_mode() is a more optimized context for inference-only workloads, as it disables autograd and activates additional internal optimizations to reduce CPU overhead and improve execution speed. This change should not affect numerical results but can lead to better runtime performance and lower memory usage during inference.
=> Replace @torch.no_grad() with @torch.inference_mode() in Qwen3-Reranker

xinference/model/audio/model_spec.json
1.经过最新的nightly-main镜像测试单独指定torch不同版本会导致flash_attn等库的cuda版本不匹配问题，且cosyvoice2生成音频问题由[transformers引起](https://github.com/FunAudioLLM/CosyVoice/issues/1546)，因此更新依赖去除对torch的约束，仅约束transformers，修改后经镜像测试可以生成正确的音频。
2.根据cosyvoice依赖[更新](https://github.com/FunAudioLLM/CosyVoice/blob/main/requirements.txt#L39)以及nightly-main镜像测试，需要增加wetext依赖，且近期wetext更新了依赖文件的处理，优化了离线下载文件的问题，因此从0.0.4升级到0.0.9
=> ENH: Update the environment dependencies for cosyvoice2

doc/source/gen_docs.py, doc/source/models/builtin/image/qwen-image-edit.rst, doc/source/models/builtin/image/qwen-image.rst, doc/source/models/builtin/llm/kat-v1.rst, doc/source/models/model_abilities/image.rst, doc/templates/image.rst.jinja, xinference/model/image/model_spec.json, xinference/model/image/stable_diffusion/core.py, xinference/model/video/model_spec.json, xinference/ui/gradio/media_interface.py
This PR introduced:
1. image2image and inpainting for qwen-image
2. inpainting UI
3. lightning models for qwen-image-edit
4. Lightning models are workable for image2image and inpainting in 4 or 8 steps.
=> FEAT: image2image and inpainting for qwen-image

xinference/model/embedding/vllm/core.py, xinference/model/embedding/vllm/tests/test_vllm_embedding.py, xinference/model/rerank/vllm/core.py
=> FEAT: Support Custom vllm embedding dim

xinference/model/llm/llm_family.json, xinference/model/llm/utils.py, xinference/model/llm/vllm/core.py
```bash
pip install vllm==0.9.2 transformers==4.53.0
SITE_PACKAGES=$(pip -V | awk '{print $4}' | sed 's/\/pip$//')
cp awq_marlin.py "$SITE_PACKAGES/vllm/model_executor/layers/quantization/awq_marlin.py"
cp deepseek_v2.py "$SITE_PACKAGES/vllm/model_executor/models/deepseek_v2.py"
```
=> FEAT: [Model] Support DeepSeek-V3.1 Quantization and tool
